<center><strong><h1 style="color:green;"> Introducción a Python </h1></strong></center>
<b><center><h1 style="color:black;"> Lubin Fernando Abaunza Melo (labaunza@unal.edu.co) </h1></center></b>
<b><center><h2 style="color:blue;"> Sede Bogotá </h2></h2></center></b>
<b><center><h2 style="color:blue;"> Facultad de Ciencias </h2></center></b>
<b><center><h2 style="color:blue;">  Departamento de Estadística </h2></center></b>

<center><a href="http://unal.edu.co/"> UN </a></center>

<b><center><h1 style="color:red;"> Personalizando el directorio de trabajo </h1></center></b>

In [1]:
import os # Importa el paquete os  (este es para determinar un direstorio de trabajo)
os.getcwd() # pregunta cual es el direstorio de trabajo

'C:\\Users\\labau\\Computacion Estadistica'

In [2]:
os.chdir("C:\\Users\\labau\\Computacion Estadistica") # nuevo direstorio de trabajo
os.getcwd() # pregunta cual es el direstorio de trabajo

'C:\\Users\\labau\\Computacion Estadistica'

<center><h1 style="color:red;"> Importación de datos  </h1></center>
<h3 style="color:red;"> Archivos con extensiones xls y xlsx </h3>

In [4]:
import pandas as pd # Importa la libreria pandas y la llama pd
import numpy as np  # Importa la libreria numpy y la llama np
pd.options.display.float_format = '{:,.2f}'.format  # Con 3f indica que quiero 3 desimales, si pongo 2f me dan 2 decimales

<h3 style="color:black;"> Documentación de pandas </h3>

In [5]:
help(pd.read_excel)

Help on function read_excel in module pandas.io.excel._base:

read_excel(io, sheet_name: 'str | int | list[IntStrT] | None' = 0, *, header: 'int | Sequence[int] | None' = 0, names: 'SequenceNotStr[Hashable] | range | None' = None, index_col: 'int | str | Sequence[int] | None' = None, usecols: 'int | str | Sequence[int] | Sequence[str] | Callable[[str], bool] | None' = None, dtype: 'DtypeArg | None' = None, engine: "Literal['xlrd', 'openpyxl', 'odf', 'pyxlsb', 'calamine'] | None" = None, converters: 'dict[str, Callable] | dict[int, Callable] | None' = None, true_values: 'Iterable[Hashable] | None' = None, false_values: 'Iterable[Hashable] | None' = None, skiprows: 'Sequence[int] | int | Callable[[int], object] | None' = None, nrows: 'int | None' = None, na_values=None, keep_default_na: 'bool' = True, na_filter: 'bool' = True, verbose: 'bool' = False, parse_dates: 'list | dict | bool' = False, date_parser: 'Callable | lib.NoDefault' = <no_default>, date_format: 'dict[Hashable, str] | str | None' = None, thousands: 'str | None' = None, decimal: 'str' = '.', comment: 'str | None' = None, skipfooter: 'int' = 0, storage_options: 'StorageOptions | None' = None, dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>, engine_kwargs: 'dict | None' = None) -> 'DataFrame | dict[IntStrT, DataFrame]'
    Read an Excel file into a ``pandas`` ``DataFrame``.

    Supports `xls`, `xlsx`, `xlsm`, `xlsb`, `odf`, `ods` and `odt` file extensions
    read from a local filesystem or URL. Supports an option to read
    a single sheet or a list of sheets.

    Parameters
    ----------
    io : str, bytes, ExcelFile, xlrd.Book, path object, or file-like object
        Any valid string path is acceptable. The string could be a URL. Valid
        URL schemes include http, ftp, s3, and file. For file URLs, a host is
        expected. A local file could be: ``file://localhost/path/to/table.xlsx``.

        If you want to pass in a path object, pandas accepts any ``os.PathLike``.

        By file-like object, we refer to objects with a ``read()`` method,
        such as a file handle (e.g. via builtin ``open`` function)
        or ``StringIO``.

        .. deprecated:: 2.1.0
            Passing byte strings is deprecated. To read from a
            byte string, wrap it in a ``BytesIO`` object.
    sheet_name : str, int, list, or None, default 0
        Strings are used for sheet names. Integers are used in zero-indexed
        sheet positions (chart sheets do not count as a sheet position).
        Lists of strings/integers are used to request multiple sheets.
        Specify ``None`` to get all worksheets.

        Available cases:

        * Defaults to ``0``: 1st sheet as a `DataFrame`
        * ``1``: 2nd sheet as a `DataFrame`
        * ``"Sheet1"``: Load sheet with name "Sheet1"
        * ``[0, 1, "Sheet5"]``: Load first, second and sheet named "Sheet5"
          as a dict of `DataFrame`
        * ``None``: All worksheets.

    header : int, list of int, default 0
        Row (0-indexed) to use for the column labels of the parsed
        DataFrame. If a list of integers is passed those row positions will
        be combined into a ``MultiIndex``. Use None if there is no header.
    names : array-like, default None
        List of column names to use. If file contains no header row,
        then you should explicitly pass header=None.
    index_col : int, str, list of int, default None
        Column (0-indexed) to use as the row labels of the DataFrame.
        Pass None if there is no such column.  If a list is passed,
        those columns will be combined into a ``MultiIndex``.  If a
        subset of data is selected with ``usecols``, index_col
        is based on the subset.

        Missing values will be forward filled to allow roundtripping with
        ``to_excel`` for ``merged_cells=True``. To avoid forward filling the
        missing values use ``set_index`` after reading the data instead of
        ``index_col``.
    usecols : str, list-like, or callable, default None
        * If None, then parse all columns.
        * If str, then indicates comma separated list of Excel column letters
          and column ranges (e.g. "A:E" or "A,C,E:F"). Ranges are inclusive of
          both sides.
        * If list of int, then indicates list of column numbers to be parsed
          (0-indexed).
        * If list of string, then indicates list of column names to be parsed.
        * If callable, then evaluate each column name against it and parse the
          column if the callable returns ``True``.

        Returns a subset of the columns according to behavior above.
    dtype : Type name or dict of column -> type, default None
        Data type for data or columns. E.g. {'a': np.float64, 'b': np.int32}
        Use ``object`` to preserve data as stored in Excel and not interpret dtype,
        which will necessarily result in ``object`` dtype.
        If converters are specified, they will be applied INSTEAD
        of dtype conversion.
        If you use ``None``, it will infer the dtype of each column based on the data.
    engine : {'openpyxl', 'calamine', 'odf', 'pyxlsb', 'xlrd'}, default None
        If io is not a buffer or path, this must be set to identify io.
        Engine compatibility :

        - ``openpyxl`` supports newer Excel file formats.
        - ``calamine`` supports Excel (.xls, .xlsx, .xlsm, .xlsb)
          and OpenDocument (.ods) file formats.
        - ``odf`` supports OpenDocument file formats (.odf, .ods, .odt).
        - ``pyxlsb`` supports Binary Excel files.
        - ``xlrd`` supports old-style Excel files (.xls).

        When ``engine=None``, the following logic will be used to determine the engine:

        - If ``path_or_buffer`` is an OpenDocument format (.odf, .ods, .odt),
          then `odf <https://pypi.org/project/odfpy/>`_ will be used.
        - Otherwise if ``path_or_buffer`` is an xls format, ``xlrd`` will be used.
        - Otherwise if ``path_or_buffer`` is in xlsb format, ``pyxlsb`` will be used.
        - Otherwise ``openpyxl`` will be used.
    converters : dict, default None
        Dict of functions for converting values in certain columns. Keys can
        either be integers or column labels, values are functions that take one
        input argument, the Excel cell content, and return the transformed
        content.
    true_values : list, default None
        Values to consider as True.
    false_values : list, default None
        Values to consider as False.
    skiprows : list-like, int, or callable, optional
        Line numbers to skip (0-indexed) or number of lines to skip (int) at the
        start of the file. If callable, the callable function will be evaluated
        against the row indices, returning True if the row should be skipped and
        False otherwise. An example of a valid callable argument would be ``lambda
        x: x in [0, 2]``.
    nrows : int, default None
        Number of rows to parse.
    na_values : scalar, str, list-like, or dict, default None
        Additional strings to recognize as NA/NaN. If dict passed, specific
        per-column NA values. By default the following values are interpreted
        as NaN: '', '#N/A', '#N/A N/A', '#NA', '-1.#IND', '-1.#QNAN', '-NaN', '-nan',
        '1.#IND', '1.#QNAN', '<NA>', 'N/A', 'NA', 'NULL', 'NaN', 'None',
        'n/a', 'nan', 'null'.
    keep_default_na : bool, default True
        Whether or not to include the default NaN values when parsing the data.
        Depending on whether ``na_values`` is passed in, the behavior is as follows:

        * If ``keep_default_na`` is True, and ``na_values`` are specified,
          ``na_values`` is appended to the default NaN values used for parsing.
        * If ``keep_default_na`` is True, and ``na_values`` are not specified, only
          the default NaN values are used for parsing.
        * If ``keep_default_na`` is False, and ``na_values`` are specified, only
          the NaN values specified ``na_values`` are used for parsing.
        * If ``keep_default_na`` is False, and ``na_values`` are not specified, no
          strings will be parsed as NaN.

        Note that if `na_filter` is passed in as False, the ``keep_default_na`` and
        ``na_values`` parameters will be ignored.
    na_filter : bool, default True
        Detect missing value markers (empty strings and the value of na_values). In
        data without any NAs, passing ``na_filter=False`` can improve the
        performance of reading a large file.
    verbose : bool, default False
        Indicate number of NA values placed in non-numeric columns.
    parse_dates : bool, list-like, or dict, default False
        The behavior is as follows:

        * ``bool``. If True -> try parsing the index.
        * ``list`` of int or names. e.g. If [1, 2, 3] -> try parsing columns 1, 2, 3
          each as a separate date column.
        * ``list`` of lists. e.g.  If [[1, 3]] -> combine columns 1 and 3 and parse as
          a single date column.
        * ``dict``, e.g. {'foo' : [1, 3]} -> parse columns 1, 3 as date and call
          result 'foo'

        If a column or index contains an unparsable date, the entire column or
        index will be returned unaltered as an object data type. If you don`t want to
        parse some cells as date just change their type in Excel to "Text".
        For non-standard datetime parsing, use ``pd.to_datetime`` after ``pd.read_excel``.

        Note: A fast-path exists for iso8601-formatted dates.
    date_parser : function, optional
        Function to use for converting a sequence of string columns to an array of
        datetime instances. The default uses ``dateutil.parser.parser`` to do the
        conversion. Pandas will try to call `date_parser` in three different ways,
        advancing to the next if an exception occurs: 1) Pass one or more arrays
        (as defined by `parse_dates`) as arguments; 2) concatenate (row-wise) the
        string values from the columns defined by `parse_dates` into a single array
        and pass that; and 3) call `date_parser` once for each row using one or
        more strings (corresponding to the columns defined by `parse_dates`) as
        arguments.

        .. deprecated:: 2.0.0
           Use ``date_format`` instead, or read in as ``object`` and then apply
           :func:`to_datetime` as-needed.
    date_format : str or dict of column -> format, default ``None``
       If used in conjunction with ``parse_dates``, will parse dates according to this
       format. For anything more complex,
       please read in as ``object`` and then apply :func:`to_datetime` as-needed.

       .. versionadded:: 2.0.0
    thousands : str, default None
        Thousands separator for parsing string columns to numeric.  Note that
        this parameter is only necessary for columns stored as TEXT in Excel,
        any numeric columns will automatically be parsed, regardless of display
        format.
    decimal : str, default '.'
        Character to recognize as decimal point for parsing string columns to numeric.
        Note that this parameter is only necessary for columns stored as TEXT in Excel,
        any numeric columns will automatically be parsed, regardless of display
        format.(e.g. use ',' for European data).

        .. versionadded:: 1.4.0

    comment : str, default None
        Comments out remainder of line. Pass a character or characters to this
        argument to indicate comments in the input file. Any data between the
        comment string and the end of the current line is ignored.
    skipfooter : int, default 0
        Rows at the end to skip (0-indexed).
    storage_options : dict, optional
        Extra options that make sense for a particular storage connection, e.g.
        host, port, username, password, etc. For HTTP(S) URLs the key-value pairs
        are forwarded to ``urllib.request.Request`` as header options. For other
        URLs (e.g. starting with "s3://", and "gcs://") the key-value pairs are
        forwarded to ``fsspec.open``. Please see ``fsspec`` and ``urllib`` for more
        details, and for more examples on storage options refer `here
        <https://pandas.pydata.org/docs/user_guide/io.html?
        highlight=storage_options#reading-writing-remote-files>`_.

    dtype_backend : {'numpy_nullable', 'pyarrow'}, default 'numpy_nullable'
        Back-end data type applied to the resultant :class:`DataFrame`
        (still experimental). Behaviour is as follows:

        * ``"numpy_nullable"``: returns nullable-dtype-backed :class:`DataFrame`
          (default).
        * ``"pyarrow"``: returns pyarrow-backed nullable :class:`ArrowDtype`
          DataFrame.

        .. versionadded:: 2.0

    engine_kwargs : dict, optional
        Arbitrary keyword arguments passed to excel engine.

    Returns
    -------
    DataFrame or dict of DataFrames
        DataFrame from the passed in Excel file. See notes in sheet_name
        argument for more information on when a dict of DataFrames is returned.

    See Also
    --------
    DataFrame.to_excel : Write DataFrame to an Excel file.
    DataFrame.to_csv : Write DataFrame to a comma-separated values (csv) file.
    read_csv : Read a comma-separated values (csv) file into DataFrame.
    read_fwf : Read a table of fixed-width formatted lines into DataFrame.

    Notes
    -----
    For specific information on the methods used for each Excel engine, refer to the pandas
    :ref:`user guide <io.excel_reader>`

    Examples
    --------
    The file can be read using the file name as string or an open file object:

    >>> pd.read_excel('tmp.xlsx', index_col=0)  # doctest: +SKIP
           Name  Value
    0   string1      1
    1   string2      2
    2  #Comment      3

    >>> pd.read_excel(open('tmp.xlsx', 'rb'),
    ...               sheet_name='Sheet3')  # doctest: +SKIP
       Unnamed: 0      Name  Value
    0           0   string1      1
    1           1   string2      2
    2           2  #Comment      3

    Index and header can be specified via the `index_col` and `header` arguments

    >>> pd.read_excel('tmp.xlsx', index_col=None, header=None)  # doctest: +SKIP
         0         1      2
    0  NaN      Name  Value
    1  0.0   string1      1
    2  1.0   string2      2
    3  2.0  #Comment      3

    Column types are inferred but can be explicitly specified

    >>> pd.read_excel('tmp.xlsx', index_col=0,
    ...               dtype={'Name': str, 'Value': float})  # doctest: +SKIP
           Name  Value
    0   string1    1.0
    1   string2    2.0
    2  #Comment    3.0

    True, False, and NA values, and thousands separators have defaults,
    but can be explicitly specified, too. Supply the values you would like
    as strings or lists of strings!

    >>> pd.read_excel('tmp.xlsx', index_col=0,
    ...               na_values=['string1', 'string2'])  # doctest: +SKIP
           Name  Value
    0       NaN      1
    1       NaN      2
    2  #Comment      3

    Comment lines in the excel input file can be skipped using the
    ``comment`` kwarg.

    >>> pd.read_excel('tmp.xlsx', index_col=0, comment='#')  # doctest: +SKIP
          Name  Value
    0  string1    1.0
    1  string2    2.0
    2     None    NaN

<h1 style="color:red;"> Ejemplo 1  </h1>
Se leen los datos disponibles en la hoja número 13 del libro de Excel <b>sample.xlsx</b>, cuya primera fila contiene los nombres de las variables.

In [6]:
plantulas1 = pd.read_excel("sample.xlsx",sheet_name=12,header=0) 
# pd.read_excel: Esta función de la biblioteca pandas se utiliza para leer un archivo de Excel y convertirlo en un DataFrame.
# "sample.xlsx": Este es el nombre del archivo de Excel que quieres leer.
# sheet_name=12: Esto especifica que deseas leer la hoja número 13 del archivo de Excel (el índice de las hojas comienza desde 0).
# header=0: Esto indica que la primera fila de la hoja debe usarse como encabezado.

plantulas1.info() # Da informacion de plantulas1

ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.

In [6]:
plantulas1.head(10) # Primeras 10 filas

   Parcela  NI  Plantula  Ni  Altura
0        3  50         1  52      12
1        3  50         2  52      11
2        3  50         3  52      12
3        3  50         4  52      10
4        3  50         5  52      13
5        6  50         6  56      10
6        6  50         7  56       9
7        6  50         8  56       7
8        6  50         9  56       9
9        6  50        10  56       8

In [7]:
plantulas1.tail(10) # Ultimas 10 filas

    Parcela  NI  Plantula  Ni  Altura
45       33  50        46  60       8
46       33  50        47  60       9
47       33  50        48  60       9
48       33  50        49  60      10
49       50  50        50  45      12
50       50  50        51  45      11
51       50  50        52  45      12
52       50  50        53  45      13
53       50  50        54  45      12
54       50  50        55  45      12

In [8]:
plantulas1.shape # Da el numero de filas y columnas

(55, 5)

In [9]:
plantulas1.columns # Vector con los nombres de las columnas

Index(['Parcela', 'NI', 'Plantula', 'Ni', 'Altura'], dtype='object')

In [10]:
plantulas1.axes

[RangeIndex(start=0, stop=55, step=1),
 Index(['Parcela', 'NI', 'Plantula', 'Ni', 'Altura'], dtype='object')]

In [11]:
plantulas1.dtypes # Tipos de variables

Parcela     int64
NI          int64
Plantula    int64
Ni          int64
Altura      int64
dtype: object

<h1 style="color:red;"> Ejemplo 2  </h1>
Se leen los datos disponibles en la hoja Plantulas del libro de Excel <b>sample.xlsx</b>, la cual corresponde a la hoja número 13 del libro.

In [12]:
plantulas2 = pd.read_excel("sample.xlsx",sheet_name="Plantulas",header=0)
plantulas2.info()
plantulas2.tail(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Parcela   55 non-null     int64
 1   NI        55 non-null     int64
 2   Plantula  55 non-null     int64
 3   Ni        55 non-null     int64
 4   Altura    55 non-null     int64
dtypes: int64(5)
memory usage: 2.3 KB

    Parcela  NI  Plantula  Ni  Altura
45       33  50        46  60       8
46       33  50        47  60       9
47       33  50        48  60       9
48       33  50        49  60      10
49       50  50        50  45      12
50       50  50        51  45      11
51       50  50        52  45      12
52       50  50        53  45      13
53       50  50        54  45      12
54       50  50        55  45      12

<h1 style="color:red;"> Ejemplo 3  </h1>

Se leen los datos en las columnas "A", "B", "C" y "E" de la hoja Plantulas del libro de Excel <b>sample.xlsx</b>.

In [13]:
plantulas3 = pd.read_excel("sample.xlsx",sheet_name="Plantulas",usecols="A:C,E",header=0)
plantulas3.info()
plantulas3.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Parcela   55 non-null     int64
 1   NI        55 non-null     int64
 2   Plantula  55 non-null     int64
 3   Altura    55 non-null     int64
dtypes: int64(4)
memory usage: 1.8 KB

   Parcela  NI  Plantula  Altura
0        3  50         1      12
1        3  50         2      11
2        3  50         3      12
3        3  50         4      10
4        3  50         5      13
5        6  50         6      10
6        6  50         7       9
7        6  50         8       7
8        6  50         9       9
9        6  50        10       8

<h1 style="color:red;"> Ejemplo 4  </h1>
Se leen solo las primeras 35 filas de datos en la hoja Plantulas del libro de Excel <b>sample.xlsx</b>.

In [14]:
plantulas4 = pd.read_excel("sample.xlsx",sheet_name="Plantulas",nrows=35,header=0)
plantulas4.info()
plantulas4.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Parcela   35 non-null     int64
 1   NI        35 non-null     int64
 2   Plantula  35 non-null     int64
 3   Ni        35 non-null     int64
 4   Altura    35 non-null     int64
dtypes: int64(5)
memory usage: 1.5 KB

   Parcela  NI  Plantula  Ni  Altura
0        3  50         1  52      12
1        3  50         2  52      11
2        3  50         3  52      12
3        3  50         4  52      10
4        3  50         5  52      13
5        6  50         6  56      10
6        6  50         7  56       9
7        6  50         8  56       7
8        6  50         9  56       9
9        6  50        10  56       8

<h1 style="color:red;"> Ejemplo 5  </h1>
Se leen los datos en la hoja Plantulas del libro de Excel <b>sample.xlsx</b> dándole nombres personalizados a las variables.

In [15]:
plantulas5 = pd.read_excel("sample.xlsx",sheet_name="Plantulas",header=0,
                           names=["IdParcela","N_I","IdPlantula","N_i","Altura"])
plantulas5.info()
plantulas5.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   IdParcela   55 non-null     int64
 1   N_I         55 non-null     int64
 2   IdPlantula  55 non-null     int64
 3   N_i         55 non-null     int64
 4   Altura      55 non-null     int64
dtypes: int64(5)
memory usage: 2.3 KB

   IdParcela  N_I  IdPlantula  N_i  Altura
0          3   50           1   52      12
1          3   50           2   52      11
2          3   50           3   52      12
3          3   50           4   52      10
4          3   50           5   52      13
5          6   50           6   56      10
6          6   50           7   56       9
7          6   50           8   56       7
8          6   50           9   56       9
9          6   50          10   56       8

<h1 style="color:red;"> Ejemplo 6  </h1>
Se leen los datos en la hoja Plantulas del libro de Excel <b>sample.xlsx</b>, dándole nombres personalizados a las variables y leyendo estas últimas con formato text, numeric, text, numeric y numeric, respectivamente.

In [16]:
plantulas6 = pd.read_excel("sample.xlsx",sheet_name="Plantulas",header=0,
                          names=["IdParcela","N_I","IdPlantula","N_i","Altura"],
                          dtype={"IdParcela":str,"N_I":np.int64,"IdPlantula":str,
                                 "N_i":np.float64,"Altura":np.float64})

# pd.read_excel: Esta función de la biblioteca pandas se usa para leer un archivo de Excel y convertirlo en un DataFrame.
# "sample.xlsx": Este es el nombre del archivo de Excel que deseas leer.
# sheet_name="Plantulas": Esto especifica que deseas leer la hoja llamada "Plantulas" dentro del archivo de Excel.
# header=0: Esto indica que la primera fila de la hoja debe usarse como encabezado.
# names=[...]: Esta lista proporciona los nombres de las columnas que deseas asignar al DataFrame.
# dtype={...}: Este diccionario especifica el tipo de datos para cada columna. En este caso:
### "IdParcela":str: La columna IdParcela será de tipo str (cadena de texto (object)).
### "N_I":np.int64: La columna N_I será de tipo np.int64 (entero de 64 bits).
### "IdPlantula":str: La columna IdPlantula será de tipo str (cadena de texto (object)).
### "N_i":np.float64: La columna N_i será de tipo np.float64 (flotante-Desimal de 64 bits).
### "Altura":np.float64: La columna Altura será de tipo np.float64 (flotante-Desimal de 64 bits).

plantulas6.info()
plantulas6.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   IdParcela   55 non-null     object
 1   N_I         55 non-null     int64
 2   IdPlantula  55 non-null     object
 3   N_i         55 non-null     float64
 4   Altura      55 non-null     float64
dtypes: float64(2), int64(1), object(2)
memory usage: 2.3+ KB

  IdParcela  N_I IdPlantula   N_i  Altura
0         3   50          1 52.00   12.00
1         3   50          2 52.00   11.00
2         3   50          3 52.00   12.00
3         3   50          4 52.00   10.00
4         3   50          5 52.00   13.00
5         6   50          6 56.00   10.00
6         6   50          7 56.00    9.00
7         6   50          8 56.00    7.00
8         6   50          9 56.00    9.00
9         6   50         10 56.00    8.00

<h1 style="color:red;"> Ejemplo 7  </h1>
Se leen los datos en la hoja Plantulas del libro de Excel <b>sample.xlsx</b>, dándole nombres personalizados a las variables y leyendo estas últimas con formato text, skip, text, guess y numeric, respectivamente. Por lo tanto, la segunda variable se excluye y el tipo de la cuarta variable se especifica a partir de una inspección de los datos.

In [17]:
plantulas7 = pd.read_excel("sample.xlsx",sheet_name="Plantulas",header=0,usecols=[0,2,3,4],
                           names=["IdParcela","IdPlantula","N_i","Altura"],
                           dtype={"IdParcela":str,"IdPlantula":str,"Altura":np.float64})
plantulas7.info()
plantulas7.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   IdParcela   55 non-null     object
 1   IdPlantula  55 non-null     object
 2   N_i         55 non-null     int64
 3   Altura      55 non-null     float64
dtypes: float64(1), int64(1), object(2)
memory usage: 1.8+ KB

  IdParcela IdPlantula  N_i  Altura
0         3          1   52   12.00
1         3          2   52   11.00
2         3          3   52   12.00
3         3          4   52   10.00
4         3          5   52   13.00
5         6          6   56   10.00
6         6          7   56    9.00
7         6          8   56    7.00
8         6          9   56    9.00
9         6         10   56    8.00

<b><h2 style="color:black;">  Archivos con extensiones txt, csv, tsv, dlm y dat </h2></b>
<b><h2 style="color:black;">  Archivos delimitados </h2></b>

In [18]:
help(pd.read_table)

Help on function read_table in module pandas.io.parsers.readers:

read_table(filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]', sep=<no_default>, delimiter=None, header='infer', names=<no_default>, index_col=None, usecols=None, squeeze=None, prefix=<no_default>, mangle_dupe_cols=True, dtype: 'DtypeArg | None' = None, engine: 'CSVEngine | None' = None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False, skip_blank_lines=True, parse_dates=False, infer_datetime_format=False, keep_date_col=False, date_parser=None, dayfirst=False, cache_dates=True, iterator=False, chunksize=None, compression: 'CompressionOptions' = 'infer', thousands=None, decimal: 'str' = '.', lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None, comment=None, encoding=None, encoding_errors: 'str | None' = 'strict', dialect=None, error_bad_lines=None, warn_bad_lines=None, on_bad_lines=None, delim_whitespace=False, low_memory=True, memory_map=False, float_precision=None, storage_options: 'StorageOptions' = None)
    Read general delimited file into DataFrame.

    Also supports optionally iterating or breaking of the file
    into chunks.

    Additional help can be found in the online docs for
    `IO Tools <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html>`_.

    Parameters
    ----------
    filepath_or_buffer : str, path object or file-like object
        Any valid string path is acceptable. The string could be a URL. Valid
        URL schemes include http, ftp, s3, gs, and file. For file URLs, a host is
        expected. A local file could be: file://localhost/path/to/table.csv.

        If you want to pass in a path object, pandas accepts any ``os.PathLike``.

        By file-like object, we refer to objects with a ``read()`` method, such as
        a file handle (e.g. via builtin ``open`` function) or ``StringIO``.
    sep : str, default '\\t' (tab-stop)
        Delimiter to use. If sep is None, the C engine cannot automatically detect
        the separator, but the Python parsing engine can, meaning the latter will
        be used and automatically detect the separator by Python's builtin sniffer
        tool, ``csv.Sniffer``. In addition, separators longer than 1 character and
        different from ``'\s+'`` will be interpreted as regular expressions and
        will also force the use of the Python parsing engine. Note that regex
        delimiters are prone to ignoring quoted data. Regex example: ``'\r\t'``.
    delimiter : str, default ``None``
        Alias for sep.
    header : int, list of int, None, default 'infer'
        Row number(s) to use as the column names, and the start of the
        data.  Default behavior is to infer the column names: if no names
        are passed the behavior is identical to ``header=0`` and column
        names are inferred from the first line of the file, if column
        names are passed explicitly then the behavior is identical to
        ``header=None``. Explicitly pass ``header=0`` to be able to
        replace existing names. The header can be a list of integers that
        specify row locations for a multi-index on the columns
        e.g. [0,1,3]. Intervening rows that are not specified will be
        skipped (e.g. 2 in this example is skipped). Note that this
        parameter ignores commented lines and empty lines if
        ``skip_blank_lines=True``, so ``header=0`` denotes the first line of
        data rather than the first line of the file.
    names : array-like, optional
        List of column names to use. If the file contains a header row,
        then you should explicitly pass ``header=0`` to override the column names.
        Duplicates in this list are not allowed.
    index_col : int, str, sequence of int / str, or False, optional, default ``None``
      Column(s) to use as the row labels of the ``DataFrame``, either given as
      string name or column index. If a sequence of int / str is given, a
      MultiIndex is used.

      Note: ``index_col=False`` can be used to force pandas to *not* use the first
      column as the index, e.g. when you have a malformed file with delimiters at
      the end of each line.
    usecols : list-like or callable, optional
        Return a subset of the columns. If list-like, all elements must either
        be positional (i.e. integer indices into the document columns) or strings
        that correspond to column names provided either by the user in `names` or
        inferred from the document header row(s). If ``names`` are given, the document
        header row(s) are not taken into account. For example, a valid list-like
        `usecols` parameter would be ``[0, 1, 2]`` or ``['foo', 'bar', 'baz']``.
        Element order is ignored, so ``usecols=[0, 1]`` is the same as ``[1, 0]``.
        To instantiate a DataFrame from ``data`` with element order preserved use
        ``pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]`` for columns
        in ``['foo', 'bar']`` order or
        ``pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]``
        for ``['bar', 'foo']`` order.

        If callable, the callable function will be evaluated against the column
        names, returning names where the callable function evaluates to True. An
        example of a valid callable argument would be ``lambda x: x.upper() in
        ['AAA', 'BBB', 'DDD']``. Using this parameter results in much faster
        parsing time and lower memory usage.
    squeeze : bool, default False
        If the parsed data only contains one column then return a Series.

        .. deprecated:: 1.4.0
            Append ``.squeeze("columns")`` to the call to ``read_table`` to squeeze
            the data.
    prefix : str, optional
        Prefix to add to column numbers when no header, e.g. 'X' for X0, X1, ...

        .. deprecated:: 1.4.0
           Use a list comprehension on the DataFrame's columns after calling ``read_csv``.
    mangle_dupe_cols : bool, default True
        Duplicate columns will be specified as 'X', 'X.1', ...'X.N', rather than
        'X'...'X'. Passing in False will cause data to be overwritten if there
        are duplicate names in the columns.
    dtype : Type name or dict of column -> type, optional
        Data type for data or columns. E.g. {'a': np.float64, 'b': np.int32,
        'c': 'Int64'}
        Use `str` or `object` together with suitable `na_values` settings
        to preserve and not interpret dtype.
        If converters are specified, they will be applied INSTEAD
        of dtype conversion.
    engine : {'c', 'python', 'pyarrow'}, optional
        Parser engine to use. The C and pyarrow engines are faster, while the python engine
        is currently more feature-complete. Multithreading is currently only supported by
        the pyarrow engine.

        .. versionadded:: 1.4.0

            The "pyarrow" engine was added as an *experimental* engine, and some features
            are unsupported, or may not work correctly, with this engine.
    converters : dict, optional
        Dict of functions for converting values in certain columns. Keys can either
        be integers or column labels.
    true_values : list, optional
        Values to consider as True.
    false_values : list, optional
        Values to consider as False.
    skipinitialspace : bool, default False
        Skip spaces after delimiter.
    skiprows : list-like, int or callable, optional
        Line numbers to skip (0-indexed) or number of lines to skip (int)
        at the start of the file.

        If callable, the callable function will be evaluated against the row
        indices, returning True if the row should be skipped and False otherwise.
        An example of a valid callable argument would be ``lambda x: x in [0, 2]``.
    skipfooter : int, default 0
        Number of lines at bottom of file to skip (Unsupported with engine='c').
    nrows : int, optional
        Number of rows of file to read. Useful for reading pieces of large files.
    na_values : scalar, str, list-like, or dict, optional
        Additional strings to recognize as NA/NaN. If dict passed, specific
        per-column NA values.  By default the following values are interpreted as
        NaN: '', '#N/A', '#N/A N/A', '#NA', '-1.#IND', '-1.#QNAN', '-NaN', '-nan',
        '1.#IND', '1.#QNAN', '<NA>', 'N/A', 'NA', 'NULL', 'NaN', 'n/a',
        'nan', 'null'.
    keep_default_na : bool, default True
        Whether or not to include the default NaN values when parsing the data.
        Depending on whether `na_values` is passed in, the behavior is as follows:

        * If `keep_default_na` is True, and `na_values` are specified, `na_values`
          is appended to the default NaN values used for parsing.
        * If `keep_default_na` is True, and `na_values` are not specified, only
          the default NaN values are used for parsing.
        * If `keep_default_na` is False, and `na_values` are specified, only
          the NaN values specified `na_values` are used for parsing.
        * If `keep_default_na` is False, and `na_values` are not specified, no
          strings will be parsed as NaN.

        Note that if `na_filter` is passed in as False, the `keep_default_na` and
        `na_values` parameters will be ignored.
    na_filter : bool, default True
        Detect missing value markers (empty strings and the value of na_values). In
        data without any NAs, passing na_filter=False can improve the performance
        of reading a large file.
    verbose : bool, default False
        Indicate number of NA values placed in non-numeric columns.
    skip_blank_lines : bool, default True
        If True, skip over blank lines rather than interpreting as NaN values.
    parse_dates : bool or list of int or names or list of lists or dict, default False
        The behavior is as follows:

        * boolean. If True -> try parsing the index.
        * list of int or names. e.g. If [1, 2, 3] -> try parsing columns 1, 2, 3
          each as a separate date column.
        * list of lists. e.g.  If [[1, 3]] -> combine columns 1 and 3 and parse as
          a single date column.
        * dict, e.g. {'foo' : [1, 3]} -> parse columns 1, 3 as date and call
          result 'foo'

        If a column or index cannot be represented as an array of datetimes,
        say because of an unparsable value or a mixture of timezones, the column
        or index will be returned unaltered as an object data type. For
        non-standard datetime parsing, use ``pd.to_datetime`` after
        ``pd.read_csv``. To parse an index or column with a mixture of timezones,
        specify ``date_parser`` to be a partially-applied
        :func:`pandas.to_datetime` with ``utc=True``. See
        :ref:`io.csv.mixed_timezones` for more.

        Note: A fast-path exists for iso8601-formatted dates.
    infer_datetime_format : bool, default False
        If True and `parse_dates` is enabled, pandas will attempt to infer the
        format of the datetime strings in the columns, and if it can be inferred,
        switch to a faster method of parsing them. In some cases this can increase
        the parsing speed by 5-10x.
    keep_date_col : bool, default False
        If True and `parse_dates` specifies combining multiple columns then
        keep the original columns.
    date_parser : function, optional
        Function to use for converting a sequence of string columns to an array of
        datetime instances. The default uses ``dateutil.parser.parser`` to do the
        conversion. Pandas will try to call `date_parser` in three different ways,
        advancing to the next if an exception occurs: 1) Pass one or more arrays
        (as defined by `parse_dates`) as arguments; 2) concatenate (row-wise) the
        string values from the columns defined by `parse_dates` into a single array
        and pass that; and 3) call `date_parser` once for each row using one or
        more strings (corresponding to the columns defined by `parse_dates`) as
        arguments.
    dayfirst : bool, default False
        DD/MM format dates, international and European format.
    cache_dates : bool, default True
        If True, use a cache of unique, converted dates to apply the datetime
        conversion. May produce significant speed-up when parsing duplicate
        date strings, especially ones with timezone offsets.

        .. versionadded:: 0.25.0
    iterator : bool, default False
        Return TextFileReader object for iteration or getting chunks with
        ``get_chunk()``.

        .. versionchanged:: 1.2

           ``TextFileReader`` is a context manager.
    chunksize : int, optional
        Return TextFileReader object for iteration.
        See the `IO Tools docs
        <https://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_
        for more information on ``iterator`` and ``chunksize``.

        .. versionchanged:: 1.2

           ``TextFileReader`` is a context manager.
    compression : str or dict, default 'infer'
        For on-the-fly decompression of on-disk data. If 'infer' and '%s' is
        path-like, then detect compression from the following extensions: '.gz',
        '.bz2', '.zip', '.xz', or '.zst' (otherwise no compression). If using
        'zip', the ZIP file must contain only one data file to be read in. Set to
        ``None`` for no decompression. Can also be a dict with key ``'method'`` set
        to one of {``'zip'``, ``'gzip'``, ``'bz2'``, ``'zstd'``} and other
        key-value pairs are forwarded to ``zipfile.ZipFile``, ``gzip.GzipFile``,
        ``bz2.BZ2File``, or ``zstandard.ZstdDecompressor``, respectively. As an
        example, the following could be passed for Zstandard decompression using a
        custom compression dictionary:
        ``compression={'method': 'zstd', 'dict_data': my_compression_dict}``.

        .. versionchanged:: 1.4.0 Zstandard support.

    thousands : str, optional
        Thousands separator.
    decimal : str, default '.'
        Character to recognize as decimal point (e.g. use ',' for European data).
    lineterminator : str (length 1), optional
        Character to break file into lines. Only valid with C parser.
    quotechar : str (length 1), optional
        The character used to denote the start and end of a quoted item. Quoted
        items can include the delimiter and it will be ignored.
    quoting : int or csv.QUOTE_* instance, default 0
        Control field quoting behavior per ``csv.QUOTE_*`` constants. Use one of
        QUOTE_MINIMAL (0), QUOTE_ALL (1), QUOTE_NONNUMERIC (2) or QUOTE_NONE (3).
    doublequote : bool, default ``True``
       When quotechar is specified and quoting is not ``QUOTE_NONE``, indicate
       whether or not to interpret two consecutive quotechar elements INSIDE a
       field as a single ``quotechar`` element.
    escapechar : str (length 1), optional
        One-character string used to escape other characters.
    comment : str, optional
        Indicates remainder of line should not be parsed. If found at the beginning
        of a line, the line will be ignored altogether. This parameter must be a
        single character. Like empty lines (as long as ``skip_blank_lines=True``),
        fully commented lines are ignored by the parameter `header` but not by
        `skiprows`. For example, if ``comment='#'``, parsing
        ``#empty\na,b,c\n1,2,3`` with ``header=0`` will result in 'a,b,c' being
        treated as the header.
    encoding : str, optional
        Encoding to use for UTF when reading/writing (ex. 'utf-8'). `List of Python
        standard encodings
        <https://docs.python.org/3/library/codecs.html#standard-encodings>`_ .

        .. versionchanged:: 1.2

           When ``encoding`` is ``None``, ``errors="replace"`` is passed to
           ``open()``. Otherwise, ``errors="strict"`` is passed to ``open()``.
           This behavior was previously only the case for ``engine="python"``.

        .. versionchanged:: 1.3.0

           ``encoding_errors`` is a new argument. ``encoding`` has no longer an
           influence on how encoding errors are handled.

    encoding_errors : str, optional, default "strict"
        How encoding errors are treated. `List of possible values
        <https://docs.python.org/3/library/codecs.html#error-handlers>`_ .

        .. versionadded:: 1.3.0

    dialect : str or csv.Dialect, optional
        If provided, this parameter will override values (default or not) for the
        following parameters: `delimiter`, `doublequote`, `escapechar`,
        `skipinitialspace`, `quotechar`, and `quoting`. If it is necessary to
        override values, a ParserWarning will be issued. See csv.Dialect
        documentation for more details.
    error_bad_lines : bool, optional, default ``None``
        Lines with too many fields (e.g. a csv line with too many commas) will by
        default cause an exception to be raised, and no DataFrame will be returned.
        If False, then these "bad lines" will be dropped from the DataFrame that is
        returned.

        .. deprecated:: 1.3.0
           The ``on_bad_lines`` parameter should be used instead to specify behavior upon
           encountering a bad line instead.
    warn_bad_lines : bool, optional, default ``None``
        If error_bad_lines is False, and warn_bad_lines is True, a warning for each
        "bad line" will be output.

        .. deprecated:: 1.3.0
           The ``on_bad_lines`` parameter should be used instead to specify behavior upon
           encountering a bad line instead.
    on_bad_lines : {'error', 'warn', 'skip'} or callable, default 'error'
        Specifies what to do upon encountering a bad line (a line with too many fields).
        Allowed values are :

            - 'error', raise an Exception when a bad line is encountered.
            - 'warn', raise a warning when a bad line is encountered and skip that line.
            - 'skip', skip bad lines without raising or warning when they are encountered.

        .. versionadded:: 1.3.0

            - callable, function with signature
              ``(bad_line: list[str]) -> list[str] | None`` that will process a single
              bad line. ``bad_line`` is a list of strings split by the ``sep``.
              If the function returns ``None``, the bad line will be ignored.
              If the function returns a new list of strings with more elements than
              expected, a ``ParserWarning`` will be emitted while dropping extra elements.
              Only supported when ``engine="python"``

        .. versionadded:: 1.4.0

    delim_whitespace : bool, default False
        Specifies whether or not whitespace (e.g. ``' '`` or ``'    '``) will be
        used as the sep. Equivalent to setting ``sep='\s+'``. If this option
        is set to True, nothing should be passed in for the ``delimiter``
        parameter.
    low_memory : bool, default True
        Internally process the file in chunks, resulting in lower memory use
        while parsing, but possibly mixed type inference.  To ensure no mixed
        types either set False, or specify the type with the `dtype` parameter.
        Note that the entire file is read into a single DataFrame regardless,
        use the `chunksize` or `iterator` parameter to return the data in chunks.
        (Only valid with C parser).
    memory_map : bool, default False
        If a filepath is provided for `filepath_or_buffer`, map the file object
        directly onto memory and access the data directly from there. Using this
        option can improve performance because there is no longer any I/O overhead.
    float_precision : str, optional
        Specifies which converter the C engine should use for floating-point

<h1 style="color:red;"> Ejemplo 8  </h1>
Se leen los datos en el archivo <b>stocks.dlm</b>, en el que los datos están separados por espacios y la primera fila contiene los nombres de las variables.

In [19]:
stocks1 = pd.read_table("stocks.dlm",delimiter=" ",header=0)
stocks1.info()
stocks1.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       699 non-null    object
 1   B       699 non-null    object
 2   C       699 non-null    object
 3   D       699 non-null    object
 4   E       699 non-null    object
 5   F       699 non-null    object
 6   G       699 non-null    object
 7   H       699 non-null    object
dtypes: object(8)
memory usage: 43.8+ KB

     A        B      C      D      E      F           G      H
0  IBM  01DEC05  89,15  89,92  81,56  82,20   5.976.252  81,37
1  IBM  01NOV05  81,85  89,94  80,64  88,90   5.556.471  88,01
2  IBM  03OCT05  80,22  84,60  78,70  81,88   7.019.666  80,86
3  IBM  01SEP05  80,16  82,11  76,93  80,22   5.772.280  79,22
4  IBM  01AUG05  83,00  84,20  79,87  80,62   4.801.386  79,62
5  IBM  01JUL05  74,30  85,11  74,16  83,46   8.056.590  82,23
6  IBM  01JUN05  75,57  77,73  73,45  74,20   6.439.536  73,10
7  IBM  02MAY05  76,88  78,11  72,50  75,55   6.896.904  74,43
8  IBM  01APR05  91,49  91,76  71,85  76,38  10.709.200  75,05
9  IBM  01MAR05  92,64  93,73  89,09  91,38   5.025.627  89,79

<h1 style="color:red;"> Ejemplo 9  </h1>
Se leen los datos en el archivo <b>stocks.dlm</b> especificando que el separador decimal es "," y el separador de agrupamiento es ".".

In [20]:
stocks2 = pd.read_table("stocks.dlm",delimiter=" ",decimal=",",thousands=".",header=0)
stocks2.info()
stocks2.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       699 non-null    object
 1   B       699 non-null    object
 2   C       699 non-null    float64
 3   D       699 non-null    float64
 4   E       699 non-null    float64
 5   F       699 non-null    float64
 6   G       699 non-null    int64
 7   H       699 non-null    float64
dtypes: float64(5), int64(1), object(2)
memory usage: 43.8+ KB

     A        B     C     D     E     F         G     H
0  IBM  01DEC05 89.15 89.92 81.56 82.20   5976252 81.37
1  IBM  01NOV05 81.85 89.94 80.64 88.90   5556471 88.01
2  IBM  03OCT05 80.22 84.60 78.70 81.88   7019666 80.86
3  IBM  01SEP05 80.16 82.11 76.93 80.22   5772280 79.22
4  IBM  01AUG05 83.00 84.20 79.87 80.62   4801386 79.62
5  IBM  01JUL05 74.30 85.11 74.16 83.46   8056590 82.23
6  IBM  01JUN05 75.57 77.73 73.45 74.20   6439536 73.10
7  IBM  02MAY05 76.88 78.11 72.50 75.55   6896904 74.43
8  IBM  01APR05 91.49 91.76 71.85 76.38  10709200 75.05
9  IBM  01MAR05 92.64 93.73 89.09 91.38   5025627 89.79

<h1 style="color:red;"> Ejemplo 10  </h1>
Se leen los datos en el archivo <b>stocks.dlm</b> especificando el formato en el que se deben leer las variables.

In [21]:
stocks3 = pd.read_table("stocks.dlm",delimiter=" ",decimal=",",thousands=".",header=0,
                        dtype={"A":str,"B":str,"C":np.float64,"D":np.float64,"E":np.float64,
                              "F":np.float64,"G":np.float64,"H":np.float64},
                        parse_dates=["B"])

stocks3.info()      
stocks3.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       699 non-null    object
 1   B       699 non-null    datetime64[ns]
 2   C       699 non-null    float64
 3   D       699 non-null    float64
 4   E       699 non-null    float64
 5   F       699 non-null    float64
 6   G       699 non-null    float64
 7   H       699 non-null    float64
dtypes: datetime64[ns](1), float64(6), object(1)
memory usage: 43.8+ KB

     A          B     C     D     E     F             G     H
0  IBM 2005-12-01 89.15 89.92 81.56 82.20  5,976,252.00 81.37
1  IBM 2005-11-01 81.85 89.94 80.64 88.90  5,556,471.00 88.01
2  IBM 2005-10-03 80.22 84.60 78.70 81.88  7,019,666.00 80.86
3  IBM 2005-09-01 80.16 82.11 76.93 80.22  5,772,280.00 79.22
4  IBM 2005-08-01 83.00 84.20 79.87 80.62  4,801,386.00 79.62
5  IBM 2005-07-01 74.30 85.11 74.16 83.46  8,056,590.00 82.23
6  IBM 2005-06-01 75.57 77.73 73.45 74.20  6,439,536.00 73.10
7  IBM 2005-05-02 76.88 78.11 72.50 75.55  6,896,904.00 74.43
8  IBM 2005-04-01 91.49 91.76 71.85 76.38 10,709,200.00 75.05
9  IBM 2005-03-01 92.64 93.73 89.09 91.38  5,025,627.00 89.79

Si la función pd.read_table() no logra reconocer el formato en que se encuentra la fecha, entonces podemos especificar ese formato usando el argumento date_format.

<h1 style="color:red;"> Formatos para Fechas y Horas </h1>

In [42]:
from datetime import datetime # Se instala el paquete para fechas

stocks3 = pd.read_table("stocks.dlm",delimiter=" ",decimal=",",thousands=".",header=0,
                        dtype={"A":str,"B":str,"C":np.float64,"D":np.float64,"E":np.float64,
                              "F":np.float64,"G":np.float64,"H":np.float64},
                        parse_dates=["B"])
# Tadabis sale mal, toca dar el formato
stocks3.info()
stocks3.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       699 non-null    object
 1   B       699 non-null    datetime64[ns]
 2   C       699 non-null    float64
 3   D       699 non-null    float64
 4   E       699 non-null    float64
 5   F       699 non-null    float64
 6   G       699 non-null    float64
 7   H       699 non-null    float64
dtypes: datetime64[ns](1), float64(6), object(1)
memory usage: 43.8+ KB

     A          B     C     D     E     F             G     H
0  IBM 2005-12-01 89.15 89.92 81.56 82.20  5,976,252.00 81.37
1  IBM 2005-11-01 81.85 89.94 80.64 88.90  5,556,471.00 88.01
2  IBM 2005-10-03 80.22 84.60 78.70 81.88  7,019,666.00 80.86
3  IBM 2005-09-01 80.16 82.11 76.93 80.22  5,772,280.00 79.22
4  IBM 2005-08-01 83.00 84.20 79.87 80.62  4,801,386.00 79.62
5  IBM 2005-07-01 74.30 85.11 74.16 83.46  8,056,590.00 82.23
6  IBM 2005-06-01 75.57 77.73 73.45 74.20  6,439,536.00 73.10
7  IBM 2005-05-02 76.88 78.11 72.50 75.55  6,896,904.00 74.43
8  IBM 2005-04-01 91.49 91.76 71.85 76.38 10,709,200.00 75.05
9  IBM 2005-03-01 92.64 93.73 89.09 91.38  5,025,627.00 89.79

<h1 style="color:red;"> Ejemplo 11 </h1>
Se leen los datos en el archivo <b>stocks.dlm</b> personalizando los nombres de las variables.

In [43]:
stocks4 = pd.read_table("stocks.dlm",delimiter=" ",header=0,decimal=",",thousands=".",
                        names=["Stock","Date","Open","High","Low","Close","Volume","AdjClose"],
                        dtype={"Stock":str,"Date":str,"Open":np.float64,"High":np.float64,
                               "Low":np.float64,"Close":np.float64,"Volume":np.float64,
                               "AdjClose":np.float64},
                        parse_dates=["Date"])
stocks4.info()
stocks4.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Stock     699 non-null    object
 1   Date      699 non-null    datetime64[ns]
 2   Open      699 non-null    float64
 3   High      699 non-null    float64
 4   Low       699 non-null    float64
 5   Close     699 non-null    float64
 6   Volume    699 non-null    float64
 7   AdjClose  699 non-null    float64
dtypes: datetime64[ns](1), float64(6), object(1)
memory usage: 43.8+ KB

  Stock       Date  Open  High   Low  Close        Volume  AdjClose
0   IBM 2005-12-01 89.15 89.92 81.56  82.20  5,976,252.00     81.37
1   IBM 2005-11-01 81.85 89.94 80.64  88.90  5,556,471.00     88.01
2   IBM 2005-10-03 80.22 84.60 78.70  81.88  7,019,666.00     80.86
3   IBM 2005-09-01 80.16 82.11 76.93  80.22  5,772,280.00     79.22
4   IBM 2005-08-01 83.00 84.20 79.87  80.62  4,801,386.00     79.62
5   IBM 2005-07-01 74.30 85.11 74.16  83.46  8,056,590.00     82.23
6   IBM 2005-06-01 75.57 77.73 73.45  74.20  6,439,536.00     73.10
7   IBM 2005-05-02 76.88 78.11 72.50  75.55  6,896,904.00     74.43
8   IBM 2005-04-01 91.49 91.76 71.85  76.38 10,709,200.00     75.05
9   IBM 2005-03-01 92.64 93.73 89.09  91.38  5,025,627.00     89.79

<center><h1 style="color:red;"> Creación y modificación de variables  </h1></center>

In [19]:
# Para traer la base de datos Municipios
Municipios = pd.read_excel("Municipios.xlsx",dtype={"Irural":np.float64,"Dep":str,
                                                    "Poblacion":np.float64,"Depmun":str})
Municipios.info()
Municipios.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1118 entries, 0 to 1117
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Departamento  1118 non-null   object
 1   Dep           1118 non-null   object
 2   Municipio     1118 non-null   object
 3   Depmun        1118 non-null   object
 4   Superficie    1117 non-null   float64
 5   Poblacion     1118 non-null   float64
 6   Irural        1118 non-null   float64
 7   Region        1118 non-null   object
dtypes: float64(3), object(5)
memory usage: 70.0+ KB

,Departamento,Dep,Municipio,Depmun,Superficie,Poblacion,Irural,Region
0,Ant%ioqUia,05,Mede&l'lín,05001,374.83,"2,483,545.00",5.00,Región Eje Cafetero
1,Ant%ioquia,05,Abej!&orr*al,05002,507.13,"20,258.00",45.00,Región Eje Cafetero
2,Ant%ioquia,05,A?br'&iaquí,05004,296.96,"2,710.00",58.00,Región Eje Cafetero
3,Ant%io>qUia,05,Alej#andr&'ía,05021,128.93,"4,669.00",48.00,Región Eje Cafetero
4,Antioquia,05,Am#a?&'*gá,05030,84.13,"30,777.00",28.00,Región Eje Cafetero
5,AntioqUia,05,Am?al#'*fi,05031,"1,209.13","26,552.00",54.00,Región Eje Cafetero
6,AntioqUia,05,Andes*!,05034,402.50,"43,713.00",38.00,Región Eje Cafetero
7,Ant%ioquia,05,&# Angelópoli?s,05036,81.88,"5,790.00",37.00,Región Eje Cafetero
8,Antioq>Uia,05,Ang#'ostura,05038,338.67,"11,462.00",47.00,Región Eje Cafetero
9,Ant%ioquia,05,An*'#?orí,05040,"1,413.77","18,737.00",58.00,Región Eje Cafetero

<h1 style="color:red;"> Ejemplo 1 </h1>
Cuales variables del conjunto de datos Municipios tienen valores perdidos o missings?

help(pd.DataFrame.apply)

In [21]:
# crea la funcion para ver si hay missings
def missings(x):
            a = sum(x.isna())
            b = 100*np.mean(x.isna()) # 
            c = pd.Series({"Missings": a,"%Missings": b})
            return(c)

In [22]:
# Aplica una función a lo largo del eje 0 (es decir, por columnas)

Municipios.apply(missings,axis=0)
# Municipios: Este es el DataFrame al que estás aplicando la función.
# .apply(missings, axis=0): El método apply de pandas aplica una función a lo largo del eje especificado. En este caso, missings es la función que estás aplicando a cada columna del DataFrame Municipios.

,Departamento,Dep,Municipio,Depmun,Superficie,Poblacion,Irural,Region
Missings,0.00,0.00,0.00,0.00,1.00,0.00,0.00,0.00
%Missings,0.00,0.00,0.00,0.00,0.09,0.00,0.00,0.00

In [23]:
# Aplica una función a lo largo del eje 1 (es decir, por filas)
Municipios.apply(missings,axis=1)

      Missings  %Missings
0         0.00       0.00
1         0.00       0.00
2         0.00       0.00
3         0.00       0.00
4         0.00       0.00
...        ...        ...
1113      0.00       0.00
1114      0.00       0.00
1115      0.00       0.00
1116      0.00       0.00
1117      0.00       0.00

[1118 rows x 2 columns]

<h1 style="color:red;"> Ejemplo 2 </h1>
Se hace "limpieza" en los nombres de los municipios, es decir,

- Se eliminan caracteres especiales.

- Se eliminan espacios al inicio y al final.

- Se reemplazan espacios múltiples por sencillos.

- Se escriben en letras minúsculas excepto en la inicial de cada palabra.

In [25]:
# Se crea una nueva varible llamada Municipios2 a la base de datos Municipios.
# Esta nueva varible corresponde a cojer la columna Municipio y "limpiarla"
Municipios["Municipio2"] = (Municipios.Municipio
                            .str.lower()
                            .str.replace("[^a-záéíóúüñ ]","", regex=True)
                            .str.replace(" +"," ", regex=True)
                            .str.strip()
                            .str.title()
                           ) 
# Municipios["Municipio2"]: Crea una nueva columna en el DataFrame Municipios llamada Municipio2.
# Municipios.Municipio: Selecciona la columna Municipio del DataFrame.
# .str.lower(): Convierte todos los caracteres de la columna Municipio a minúsculas.
# .str.replace("[^a-záéíóúüñ ]","", regex=True): Elimina todos los caracteres que no sean letras (incluyendo caracteres acentuados) o espacios.
# .str.replace(" +"," ", regex=True): Reemplaza cualquier secuencia de uno o más espacios por un solo espacio.
# .str.strip(): Elimina los espacios en blanco al inicio y al final de cada valor de la columna.
# .str.title(): Convierte la primera letra de cada palabra en mayúscula.


Municipios[["Municipio","Municipio2"]].tail(10) # Muestra las columna Municipio y Municipio2

                     Municipio      Municipio2
1108                   M*it!ú             Mitú
1109                 C!a*#ruru          Caruru
1110                P*a!coa              Pacoa
1111           Tara#?ir&*a'            Taraira
1112                Papuna!ua         Papunaua
1113            Y#*ava'ra?t!é         Yavaraté
1114     Puerto   Carr#eño'     Puerto Carreño
1115         La Prima&*'!ve#ra    La Primavera
1116          Santa   ?Rosalía   Santa Rosalía
1117              C#u'?mar!ibo        Cumaribo

In [26]:
Municipios["Municipio"] = Municipios["Municipio2"] # Se hae que la columna Municipios sea igual a Municipios2
Municipios = Municipios.drop(columns="Municipio2") # Se elimina la columna Municipos2
Municipios.tail(10)

,Departamento,Dep,Municipio,Depmun,Superficie,Poblacion,Irural,Region
1108,Vaupés,97,Mitú,97001.0,"16,215.74","31,302.00",77.00,Región Llano
1109,Va%Up>és,97,Caruru,97161.0,"6,368.49","3,056.00",85.00,Región Llano
1110,Vaup>és,97,Pacoa,97511.0,"13,993.25","4,229.00",91.00,Región Llano
1111,Vaupés,97,Taraira,97666.0,"6,510.25","2,318.00",97.00,Región Llano
1112,Va%Upés,97,Papunaua,97777.0,"5,551.15",749.00,95.00,Región Llano
1113,Vaup>és,97,Yavaraté,97889.0,"4,660.41","1,067.00",92.00,Región Llano
1114,Vi%ch>ada,99,Puerto Carreño,99001.0,"12,204.95","20,474.00",81.00,Región Llano
1115,Vichada,99,La Primavera,99524.0,"18,569.34","9,799.00",85.00,Región Llano
1116,Vi%ch>ada,99,Santa Rosalía,99624.0,"3,691.87","4,130.00",81.00,Región Llano
1117,Vichada,99,Cumaribo,99773.0,"65,597.21","76,196.00",87.00,Región Llano

<h1 style="color:red;"> Ejemplo 3 </h1>
Se hace "limpieza" en los nombres de los departamentos, es decir,

- Se eliminan caracteres especiales.

- Se eliminan espacios al inicio y al final.

- Se reemplazan espacios múltiples por sencillos.

- Se escriben en letras minúsculas excepto en la inicial de cada palabra.

In [27]:
Municipios["Departamento2"] = (Municipios.Departamento
                               .str.lower()
                               .str.replace("[^a-záéíóúüñ ]","", regex=True)
                               .str.replace(" +"," ", regex=True)
                               .str.strip()
                               .str.title()
                              ) 
Municipios[["Departamento","Departamento2"]].head(10)

    Departamento Departamento2
0     Ant%ioqUia     Antioquia
1     Ant%ioquia     Antioquia
2     Ant%ioquia     Antioquia
3    Ant%io>qUia     Antioquia
4      Antioquia     Antioquia
5      AntioqUia     Antioquia
6      AntioqUia     Antioquia
7  Ant%ioquia        Antioquia
8     Antioq>Uia     Antioquia
9    Ant%ioquia      Antioquia

In [28]:
Municipios["Departamento"] = Municipios["Departamento2"]
Municipios = Municipios.drop(columns="Departamento2")
Municipios.head(10)

,Departamento,Dep,Municipio,Depmun,Superficie,Poblacion,Irural,Region
0,Antioquia,05,Medellín,05001,374.83,"2,483,545.00",5.00,Región Eje Cafetero
1,Antioquia,05,Abejorral,05002,507.13,"20,258.00",45.00,Región Eje Cafetero
2,Antioquia,05,Abriaquí,05004,296.96,"2,710.00",58.00,Región Eje Cafetero
3,Antioquia,05,Alejandría,05021,128.93,"4,669.00",48.00,Región Eje Cafetero
4,Antioquia,05,Amagá,05030,84.13,"30,777.00",28.00,Región Eje Cafetero
5,Antioquia,05,Amalfi,05031,"1,209.13","26,552.00",54.00,Región Eje Cafetero
6,Antioquia,05,Andes,05034,402.50,"43,713.00",38.00,Región Eje Cafetero
7,Antioquia,05,Angelópolis,05036,81.88,"5,790.00",37.00,Región Eje Cafetero
8,Antioquia,05,Angostura,05038,338.67,"11,462.00",47.00,Región Eje Cafetero
9,Antioquia,05,Anorí,05040,"1,413.77","18,737.00",58.00,Región Eje Cafetero

<h1 style="color:red;"> Ejemplo 4 </h1>
Se hace "limpieza" en los nombres de las regiones, es decir,

- Se eliminan caracteres especiales.

- Se eliminan espacios al inicio y al final.

- Se reemplazan espacios múltiples por sencillos.

- Se escriben en letras minúsculas excepto en la inicial de cada palabra.

In [29]:
Municipios["Region"] = (Municipios.Region
                        .str.lower()
                        .str.replace("[^a-záéíóúüñ ]","", regex=True)
                        .str.replace(" +"," ", regex=True)
                        .str.replace("región ","", regex=True) # Elimina la palabra región
                        .str.strip()
                        .str.title()
                       )
Municipios.head(10)

,Departamento,Dep,Municipio,Depmun,Superficie,Poblacion,Irural,Region
0,Antioquia,05,Medellín,05001,374.83,"2,483,545.00",5.00,Eje Cafetero
1,Antioquia,05,Abejorral,05002,507.13,"20,258.00",45.00,Eje Cafetero
2,Antioquia,05,Abriaquí,05004,296.96,"2,710.00",58.00,Eje Cafetero
3,Antioquia,05,Alejandría,05021,128.93,"4,669.00",48.00,Eje Cafetero
4,Antioquia,05,Amagá,05030,84.13,"30,777.00",28.00,Eje Cafetero
5,Antioquia,05,Amalfi,05031,"1,209.13","26,552.00",54.00,Eje Cafetero
6,Antioquia,05,Andes,05034,402.50,"43,713.00",38.00,Eje Cafetero
7,Antioquia,05,Angelópolis,05036,81.88,"5,790.00",37.00,Eje Cafetero
8,Antioquia,05,Angostura,05038,338.67,"11,462.00",47.00,Eje Cafetero
9,Antioquia,05,Anorí,05040,"1,413.77","18,737.00",58.00,Eje Cafetero

<h1 style="color:red;"> Ejemplo 5 </h1>
Se crea la variable Tipo igual a: (i) "Capital" para la capital de cada departamento; y (ii) "Otro" para el resto de los municipios.

In [30]:
# Se crea una nueva funcion para poner Capital u Otro
def tipo(x): 
    if x[2:5]=="001" and x!="25001": return("Capital") # Se pone x[2:5], ya que pyton cuenta desde 0 -> laposicion 2 es la 3; se pone 5 ya que esta ultima no la tiene en cuanta -> 5 = 4 (Contando desde 0)
    else: return("Otros")
    
Municipios["Tipo"] = Municipios["Depmun"].apply(tipo)

Municipios.info()
Municipios.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1118 entries, 0 to 1117
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Departamento  1118 non-null   object
 1   Dep           1118 non-null   object
 2   Municipio     1118 non-null   object
 3   Depmun        1118 non-null   object
 4   Superficie    1117 non-null   float64
 5   Poblacion     1118 non-null   float64
 6   Irural        1118 non-null   float64
 7   Region        1118 non-null   object
 8   Tipo          1118 non-null   object
dtypes: float64(3), object(6)
memory usage: 78.7+ KB

,Departamento,Dep,Municipio,Depmun,Superficie,Poblacion,Irural,Region,Tipo
0,Antioquia,05,Medellín,05001,374.83,"2,483,545.00",5.00,Eje Cafetero,Capital
1,Antioquia,05,Abejorral,05002,507.13,"20,258.00",45.00,Eje Cafetero,Otros
2,Antioquia,05,Abriaquí,05004,296.96,"2,710.00",58.00,Eje Cafetero,Otros
3,Antioquia,05,Alejandría,05021,128.93,"4,669.00",48.00,Eje Cafetero,Otros
4,Antioquia,05,Amagá,05030,84.13,"30,777.00",28.00,Eje Cafetero,Otros
5,Antioquia,05,Amalfi,05031,"1,209.13","26,552.00",54.00,Eje Cafetero,Otros
6,Antioquia,05,Andes,05034,402.50,"43,713.00",38.00,Eje Cafetero,Otros
7,Antioquia,05,Angelópolis,05036,81.88,"5,790.00",37.00,Eje Cafetero,Otros
8,Antioquia,05,Angostura,05038,338.67,"11,462.00",47.00,Eje Cafetero,Otros
9,Antioquia,05,Anorí,05040,"1,413.77","18,737.00",58.00,Eje Cafetero,Otros

<h1 style="color:red;"> Ejemplo 6 </h1>
Se crea la variable denspobl definida como el cociente entre Poblacion y Superficie. Se crea también la variable Zona definida como: (i) "Urbano" cuando Irural  <= 40 ; y (ii) "Rural" cuando Irural  >40 .

In [36]:
# Se crea la columna "denspobl"
Municipios["denspobl"] = Municipios["Poblacion"]/Municipios["Superficie"]

In [37]:
def zona(x): 
    if x  > 40: return("Rural")
    if x <= 40: return("Urbano")
    
Municipios["Zona"] = Municipios["Irural"].apply(zona)
Municipios.head(10)

,Departamento,Dep,Municipio,Depmun,Superficie,Poblacion,Irural,Region,Tipo,Zona2,denspobl,Zona
0,Antioquia,05,Medellín,05001,374.83,"2,483,545.00",5.00,Eje Cafetero,Capital,Urbano,"6,625.78",Urbano
1,Antioquia,05,Abejorral,05002,507.13,"20,258.00",45.00,Eje Cafetero,Otros,Rural,39.95,Rural
2,Antioquia,05,Abriaquí,05004,296.96,"2,710.00",58.00,Eje Cafetero,Otros,Rural,9.13,Rural
3,Antioquia,05,Alejandría,05021,128.93,"4,669.00",48.00,Eje Cafetero,Otros,Rural,36.21,Rural
4,Antioquia,05,Amagá,05030,84.13,"30,777.00",28.00,Eje Cafetero,Otros,Urbano,365.82,Urbano
5,Antioquia,05,Amalfi,05031,"1,209.13","26,552.00",54.00,Eje Cafetero,Otros,Rural,21.96,Rural
6,Antioquia,05,Andes,05034,402.50,"43,713.00",38.00,Eje Cafetero,Otros,Urbano,108.60,Urbano
7,Antioquia,05,Angelópolis,05036,81.88,"5,790.00",37.00,Eje Cafetero,Otros,Urbano,70.72,Urbano
8,Antioquia,05,Angostura,05038,338.67,"11,462.00",47.00,Eje Cafetero,Otros,Rural,33.84,Rural
9,Antioquia,05,Anorí,05040,"1,413.77","18,737.00",58.00,Eje Cafetero,Otros,Rural,13.25,Rural

In [38]:
# Otra forma de hacer lo anterior
Municipios.loc[Municipios.Irural >  40,"Zona2"] = "Rural" 
Municipios.loc[Municipios.Irural <= 40,"Zona2"] = "Urbano"
Municipios.head(10)

,Departamento,Dep,Municipio,Depmun,Superficie,Poblacion,Irural,Region,Tipo,Zona2,denspobl,Zona
0,Antioquia,05,Medellín,05001,374.83,"2,483,545.00",5.00,Eje Cafetero,Capital,Urbano,"6,625.78",Urbano
1,Antioquia,05,Abejorral,05002,507.13,"20,258.00",45.00,Eje Cafetero,Otros,Rural,39.95,Rural
2,Antioquia,05,Abriaquí,05004,296.96,"2,710.00",58.00,Eje Cafetero,Otros,Rural,9.13,Rural
3,Antioquia,05,Alejandría,05021,128.93,"4,669.00",48.00,Eje Cafetero,Otros,Rural,36.21,Rural
4,Antioquia,05,Amagá,05030,84.13,"30,777.00",28.00,Eje Cafetero,Otros,Urbano,365.82,Urbano
5,Antioquia,05,Amalfi,05031,"1,209.13","26,552.00",54.00,Eje Cafetero,Otros,Rural,21.96,Rural
6,Antioquia,05,Andes,05034,402.50,"43,713.00",38.00,Eje Cafetero,Otros,Urbano,108.60,Urbano
7,Antioquia,05,Angelópolis,05036,81.88,"5,790.00",37.00,Eje Cafetero,Otros,Urbano,70.72,Urbano
8,Antioquia,05,Angostura,05038,338.67,"11,462.00",47.00,Eje Cafetero,Otros,Rural,33.84,Rural
9,Antioquia,05,Anorí,05040,"1,413.77","18,737.00",58.00,Eje Cafetero,Otros,Rural,13.25,Rural

In [39]:
# Me indica si son iguales la columnas Zona y Zona2
Municipios["Zona"].equals(Municipios["Zona2"])

True

In [40]:
# Elimina la columna Zona2
Municipios = Municipios.drop(columns="Zona2")

<center><h1 style="color:red;"> Funciones de texto  </h1></center>

<h1 style="color:red;"> Ejemplo 1 </h1>
Conjunto de datos con las variables Departamento, Depmun y Municipio, y con todos los municipios cuyo nombre incluye el nombre de un santo, por ejemplo, Santa Marta, Santo Tomás, San José y Valle de San Jacinto.

In [41]:
import warnings # Importa la libreria necesaria
warnings.filterwarnings("ignore") # Para que no salga el chorrero

In [42]:
santos = (Municipios
          .query("Municipio.str.contains('(^| )San( |ta |to )').values")
          .loc[:,["Departamento","Depmun","Municipio"]]
          .reset_index(drop=True) # Para que el nuevo bataframe tenga una nueva enumeracion; si lo quito, inica desde la pocicion en la que esta el priner departamento con el nombre de una santo
         )
santos.info()
santos.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Departamento  111 non-null    object
 1   Depmun        111 non-null    object
 2   Municipio     111 non-null    object
dtypes: object(3)
memory usage: 2.7+ KB

  Departamento Depmun               Municipio
0    Antioquia  05647  San Andrés De Cuerquía
1    Antioquia  05649              San Carlos
2    Antioquia  05652           San Francisco
3    Antioquia  05656            San Jerónimo
4    Antioquia  05658  San José De La Montaña
5    Antioquia  05659       San Juan De Urabá
6    Antioquia  05660                San Luis
7    Antioquia  05664               San Pedro
8    Antioquia  05665      San Pedro De Uraba
9    Antioquia  05667              San Rafael

<h1 style="color:red;"> Ejemplo 2 </h1>
Conjunto de datos con las variables Departamento, Depmun y Municipio, y con todos los municipios cuyos nombres inician y terminan con la misma vocal.

In [61]:
t = str.maketrans({"á":"a","é":"e","í":"i","ó":"o","ú":"u"})
def trans(x):
    return(str.lower(x).translate(t))
Municipios["Municipio2"] = Municipios["Municipio"].apply(trans)
Municipios["Iguales"] = Municipios["Municipio2"].str.get(0) == Municipios["Municipio2"].str.get(-1)

In [62]:
voc = (Municipios
      .query("Iguales & Municipio2.str.contains('^(a|e|i|o|u)').values")
      .loc[:,["Dep","Departamento","Depmun","Municipio"]] 
      .reset_index(drop=True)
      )
voc.info()
voc.head(15)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Dep           39 non-null     object
 1   Departamento  39 non-null     object
 2   Depmun        39 non-null     object
 3   Municipio     39 non-null     object
dtypes: object(4)
memory usage: 1.3+ KB

   Dep Departamento   Depmun   Municipio
0   05    Antioquia    05021  Alejandría
1   05    Antioquia    05030       Amagá
2   05    Antioquia    05038   Angostura
3   05    Antioquia    05044        Anza
4   05    Antioquia    05055     Argelia
5   05    Antioquia    05059     Armenia
6   05    Antioquia    05250    El Bagre
7   05    Antioquia    05360      Itagui
8   13      Bolívar  13052.0      Arjona
9   15       Boyacá  15022.0     Almeida
10  15       Boyacá  15047.0   Aquitania
11  17       Caldas  17042.0     Anserma
12  18      Caquetá  18029.0     Albania
13  19        Cauca  19050.0     Argelia
14  20        Cesar  20011.0   Aguachica

<h1 style="color:red;"> Ejemplo 3 </h1>
Conjunto de datos con todos los municipios cuyos nombres inician y terminan con la misma consonante.

In [63]:
consonantes  = (Municipios
      .query("Iguales & ~Municipio2.str.contains('^(a|e|i|o|u)').values")
      .loc[:,["Dep","Departamento","Depmun","Municipio"]]
      .reset_index(drop=True)
      )
consonantes.info()
consonantes.head(15)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Dep           17 non-null     object
 1   Departamento  17 non-null     object
 2   Depmun        17 non-null     object
 3   Municipio     17 non-null     object
dtypes: object(4)
memory usage: 672.0+ bytes

   Dep        Departamento   Depmun           Municipio
0   05           Antioquia    05649          San Carlos
1   05           Antioquia    05660            San Luis
2   05           Antioquia    05686  Santa Rosa De Osos
3   08           Atlántico    08685         Santo Tomás
4   13             Bolívar  13580.0             Regidor
5   15              Boyacá  15494.0         Nuevo Colón
6   23             Córdoba  23678.0          San Carlos
7   25        Cundinamarca  25486.0             Nemocón
8   52              Nariño  52720.0             Sapuyes
9   54  Norte De Santander  54743.0               Silos
10  68           Santander  68655.0    Sabana De Torres
11  68           Santander  68669.0          San Andrés
12  70               Sucre  70670.0             Sampués
13  70               Sucre  70708.0          San Marcos
14  73              Tolima  73678.0            San Luis

<h1 style="color:red;"> Ejemplo 4 </h1>
Conjunto de datos con todas las variables excepto Poblacion, Superficie y Irural, y con todos los municipios cuyos nombres tienen "A" como primera letra y "e" como cuarta letra.

In [64]:
Aes = (Municipios
       .query("Municipio.str.contains('^(A|Á).{2}(e|é)').values")
       .drop(columns=["Poblacion","Superficie","Irural"])
       .reset_index(drop=True)
      )
Aes.info()
Aes.head(15)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Departamento  15 non-null     object
 1   Dep           15 non-null     object
 2   Municipio     15 non-null     object
 3   Depmun        15 non-null     object
 4   Region        15 non-null     object
 5   Tipo          15 non-null     object
 6   denspobl      15 non-null     float64
 7   Zona          15 non-null     object
 8   Municipio2    15 non-null     object
 9   Iguales       15 non-null     bool
dtypes: bool(1), float64(1), object(8)
memory usage: 1.2+ KB

,Departamento,Dep,Municipio,Depmun,Region,Tipo,denspobl,Zona,Municipio2,Iguales
0,Antioquia,05,Andes,05034,Eje Cafetero,Otros,108.60,Urbano,andes,False
1,Antioquia,05,Angelópolis,05036,Eje Cafetero,Otros,70.72,Urbano,angelopolis,False
2,Antioquia,05,Argelia,05055,Eje Cafetero,Otros,30.88,Rural,argelia,True
3,Antioquia,05,Armenia,05059,Eje Cafetero,Otros,46.05,Rural,armenia,True
4,Boyacá,15,Almeida,15022.0,Centro Oriente,Otros,31.99,Rural,almeida,True
5,Caldas,17,Anserma,17042.0,Eje Cafetero,Otros,174.07,Urbano,anserma,True
6,Cauca,19,Argelia,19050.0,Pacífico,Otros,34.00,Rural,argelia,True
7,Cundinamarca,25,Arbeláez,25053.0,Centro Oriente,Otros,75.99,Urbano,arbelaez,False
8,Huila,41,Aipe,41016.0,Centro Sur,Otros,20.56,Rural,aipe,False
9,Huila,41,Algeciras,41020.0,Centro Sur,Otros,38.15,Rural,algeciras,False
10,Norte De Santander,54,Abrego,54003.0,Centro Oriente,Otros,23.87,Rural,abrego,False
11,Quindío,63,Armenia,63001.0,Eje Cafetero,Capital,"2,468.35",Urbano,armenia,True
12,Tolima,73,Armero,73055.0,Centro Sur,Otros,27.99,Rural,armero,False
13,Valle Del Cauca,76,Ansermanuevo,76041.0,Pacífico,Otros,56.79,Rural,ansermanuevo,False
14,Valle Del Cauca,76,Argelia,76054.0,Pacífico,Otros,57.91,Rural,argelia,True

<h1 style="color:red;"> Ejemplo 5 </h1>
Cuales municipios tienen nombres que constan de más de 4 palabras?

In [65]:
Mas4 = (Municipios
        .query("Municipio.str.count(' ').values > 3")
        .reset_index(drop=True)
       )
Mas4.info()
Mas4

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Departamento  5 non-null      object
 1   Dep           5 non-null      object
 2   Municipio     5 non-null      object
 3   Depmun        5 non-null      object
 4   Superficie    5 non-null      float64
 5   Poblacion     5 non-null      float64
 6   Irural        5 non-null      float64
 7   Region        5 non-null      object
 8   Tipo          5 non-null      object
 9   denspobl      5 non-null      float64
 10  Zona          5 non-null      object
 11  Municipio2    5 non-null      object
 12  Iguales       5 non-null      bool
dtypes: bool(1), float64(4), object(8)
memory usage: 613.0+ bytes

,Departamento,Dep,Municipio,Depmun,Superficie,Poblacion,Irural,Region,Tipo,denspobl,Zona,Municipio2,Iguales
0,Antioquia,05,San José De La Montaña,05658,126.07,"3,706.00",50.00,Eje Cafetero,Otros,29.40,Rural,san jose de la montaña,False
1,Cundinamarca,25,San Juan De Río Seco,25662.0,314.09,"8,324.00",47.00,Centro Oriente,Otros,26.50,Rural,san juan de rio seco,False
2,Cundinamarca,25,Villa De San Diego De Ubate,25843.0,102.28,"44,802.00",29.00,Centro Oriente,Otros,438.05,Urbano,villa de san diego de ubate,False
3,Chocó,27,El Cantón Del San Pablo,27135.0,380.50,"6,210.00",54.00,Pacífico,Otros,16.32,Rural,el canton del san pablo,False
4,Chocó,27,El Litoral Del San Juan,27250.0,"4,134.98","22,242.00",67.00,Pacífico,Otros,5.38,Rural,el litoral del san juan,False

<h1 style="color:red;"> Ejemplo 6 </h1>
Conjunto de datos con las variables Departamento, Depmun y Municipio, y con el 1% de municipios con los nombres más largos.

In [66]:
long = Municipios["Municipio"].str.len()
largos = (Municipios
          .query("@long > @long.quantile(0.99)")
          .loc[:,["Departamento","Depmun","Municipio"]]
          .reset_index(drop=True)
         )
largos

   Departamento   Depmun                    Municipio
0       Córdoba  23675.0      San Bernardo Del Viento
1  Cundinamarca  25645.0   San Antonio Del Tequendama
2  Cundinamarca  25843.0  Villa De San Diego De Ubate
3         Chocó  27135.0      El Cantón Del San Pablo
4         Chocó  27250.0      El Litoral Del San Juan
5     Magdalena  47692.0  San Sebastián De Buenavista

<h1 style="color:red;"> Ejemplo 7 </h1>
Conjunto de datos con las variables Departamento, Depmun y Municipio, y con el 1% de municipios con los nombres más cortos.

In [67]:
cortos = (Municipios
          .query("@long <= @long.quantile(0.01)")
          .loc[:,["Departamento","Depmun","Municipio"]]
          .reset_index(drop=True)
         )
cortos

          Departamento   Depmun Municipio
0            Antioquia    05044      Anza
1            Antioquia    05885      Yalí
2            Atlántico    08770      Suan
3              Bolívar  13006.0      Achí
4               Boyacá  15362.0       Iza
5               Boyacá  15480.0      Muzo
6               Boyacá  15514.0      Páez
7               Boyacá  15533.0      Paya
8               Boyacá  15762.0      Sora
9               Boyacá  15814.0      Toca
10              Boyacá  15822.0      Tota
11              Boyacá  15837.0      Tuta
12               Cauca  19355.0      Inzá
13               Cauca  19517.0      Páez
14        Cundinamarca  25175.0      Chía
15        Cundinamarca  25214.0      Cota
16        Cundinamarca  25299.0      Gama
17        Cundinamarca  25488.0      Nilo
18        Cundinamarca  25580.0      Pulí
19        Cundinamarca  25758.0      Sopó
20        Cundinamarca  25779.0      Susa
21        Cundinamarca  25797.0      Tena
22        Cundinamarca  25845.0       Une
23               Chocó  27745.0      Sipí
24               Chocó  27787.0      Tadó
25               Huila  41016.0      Aipe
26               Huila  41349.0      Hobo
27              Nariño  52352.0      Iles
28  Norte De Santander  54810.0      Tibú
29           Risaralda  66045.0      Apía
30           Santander  68344.0      Hato
31           Santander  68500.0      Oiba
32           Santander  68820.0      Tona
33     Valle Del Cauca  76001.0      Cali
34     Valle Del Cauca  76823.0      Toro
35              Arauca  81794.0      Tame
36            Casanare  85139.0      Maní
37            Casanare  85263.0      Pore
38              Vaupés  97001.0      Mitú

<center><h1 style="color:red;"> Estadísticas descriptivas  </h1></center>

<h1 style="color:red;"> Ejemplo 1 </h1>
Cálculo de algunas estadísticas descriptivas para las variables numéricas en el conjunto de datos Municipios.

In [68]:
help(pd.DataFrame.describe)

Help on function describe in module pandas.core.generic:

describe(self: 'NDFrameT', percentiles=None, include=None, exclude=None, datetime_is_numeric=False) -> 'NDFrameT'
    Generate descriptive statistics.

    Descriptive statistics include those that summarize the central
    tendency, dispersion and shape of a
    dataset's distribution, excluding ``NaN`` values.

    Analyzes both numeric and object series, as well
    as ``DataFrame`` column sets of mixed data types. The output
    will vary depending on what is provided. Refer to the notes
    below for more detail.

    Parameters
    ----------
    percentiles : list-like of numbers, optional
        The percentiles to include in the output. All should
        fall between 0 and 1. The default is
        ``[.25, .5, .75]``, which returns the 25th, 50th, and
        75th percentiles.
    include : 'all', list-like of dtypes or None (default), optional
        A white list of data types to include in the result. Ignored
        for ``Series``. Here are the options:

        - 'all' : All columns of the input will be included in the output.
        - A list-like of dtypes : Limits the results to the
          provided data types.
          To limit the result to numeric types submit
          ``numpy.number``. To limit it instead to object columns submit
          the ``numpy.object`` data type. Strings
          can also be used in the style of
          ``select_dtypes`` (e.g. ``df.describe(include=['O'])``). To
          select pandas categorical columns, use ``'category'``
        - None (default) : The result will include all numeric columns.
    exclude : list-like of dtypes or None (default), optional,
        A black list of data types to omit from the result. Ignored
        for ``Series``. Here are the options:

        - A list-like of dtypes : Excludes the provided data types
          from the result. To exclude numeric types submit
          ``numpy.number``. To exclude object columns submit the data
          type ``numpy.object``. Strings can also be used in the style of
          ``select_dtypes`` (e.g. ``df.describe(exclude=['O'])``). To
          exclude pandas categorical columns, use ``'category'``
        - None (default) : The result will exclude nothing.
    datetime_is_numeric : bool, default False
        Whether to treat datetime dtypes as numeric. This affects statistics
        calculated for the column. For DataFrame input, this also
        controls whether datetime columns are included by default.

        .. versionadded:: 1.1.0

    Returns
    -------
    Series or DataFrame
        Summary statistics of the Series or Dataframe provided.

    See Also
    --------
    DataFrame.count: Count number of non-NA/null observations.
    DataFrame.max: Maximum of the values in the object.
    DataFrame.min: Minimum of the values in the object.
    DataFrame.mean: Mean of the values.
    DataFrame.std: Standard deviation of the observations.
    DataFrame.select_dtypes: Subset of a DataFrame including/excluding
        columns based on their dtype.

    Notes
    -----
    For numeric data, the result's index will include ``count``,
    ``mean``, ``std``, ``min``, ``max`` as well as lower, ``50`` and
    upper percentiles. By default the lower percentile is ``25`` and the
    upper percentile is ``75``. The ``50`` percentile is the
    same as the median.

    For object data (e.g. strings or timestamps), the result's index
    will include ``count``, ``unique``, ``top``, and ``freq``. The ``top``
    is the most common value. The ``freq`` is the most common value's
    frequency. Timestamps also include the ``first`` and ``last`` items.

    If multiple object values have the highest count, then the
    ``count`` and ``top`` results will be arbitrarily chosen from
    among those with the highest count.

    For mixed data types provided via a ``DataFrame``, the default is to
    return only an analysis of numeric columns. If the dataframe consists
    only of object and categorical data without any numeric columns, the
    default is to return an analysis of both the object and categorical
    columns. If ``include='all'`` is provided as an option, the result
    will include a union of attributes of each type.

    The `include` and `exclude` parameters can be used to limit
    which columns in a ``DataFrame`` are analyzed for the output.
    The parameters are ignored when analyzing a ``Series``.

    Examples
    --------
    Describing a numeric ``Series``.

    >>> s = pd.Series([1, 2, 3])
    >>> s.describe()
    count    3.0
    mean     2.0
    std      1.0
    min      1.0
    25%      1.5
    50%      2.0
    75%      2.5
    max      3.0
    dtype: float64

    Describing a categorical ``Series``.

    >>> s = pd.Series(['a', 'a', 'b', 'c'])
    >>> s.describe()
    count     4
    unique    3
    top       a
    freq      2
    dtype: object

    Describing a timestamp ``Series``.

    >>> s = pd.Series([
    ...   np.datetime64("2000-01-01"),
    ...   np.datetime64("2010-01-01"),
    ...   np.datetime64("2010-01-01")
    ... ])
    >>> s.describe(datetime_is_numeric=True)
    count                      3
    mean     2006-09-01 08:00:00
    min      2000-01-01 00:00:00
    25%      2004-12-31 12:00:00
    50%      2010-01-01 00:00:00
    75%      2010-01-01 00:00:00
    max      2010-01-01 00:00:00
    dtype: object

    Describing a ``DataFrame``. By default only numeric fields
    are returned.

    >>> df = pd.DataFrame({'categorical': pd.Categorical(['d','e','f']),
    ...                    'numeric': [1, 2, 3],
    ...                    'object': ['a', 'b', 'c']
    ...                   })
    >>> df.describe()
           numeric
    count      3.0
    mean       2.0
    std        1.0
    min        1.0
    25%        1.5
    50%        2.0
    75%        2.5
    max        3.0

    Describing all columns of a ``DataFrame`` regardless of data type.

    >>> df.describe(include='all')  # doctest: +SKIP
           categorical  numeric object
    count            3      3.0      3
    unique           3      NaN      3
    top              f      NaN      a
    freq             1      NaN      1
    mean           NaN      2.0    NaN
    std            NaN      1.0    NaN
    min            NaN      1.0    NaN
    25%            NaN      1.5    NaN
    50%            NaN      2.0    NaN
    75%            NaN      2.5    NaN
    max            NaN      3.0    NaN

    Describing a column from a ``DataFrame`` by accessing it as
    an attribute.

    >>> df.numeric.describe()
    count    3.0
    mean     2.0
    std      1.0
    min      1.0
    25%      1.5
    50%      2.0
    75%      2.5
    max      3.0
    Name: numeric, dtype: float64

    Including only numeric columns in a ``DataFrame`` description.

    >>> df.describe(include=[np.number])
           numeric
    count      3.0
    mean       2.0
    std        1.0
    min        1.0
    25%        1.5
    50%        2.0
    75%        2.5
    max        3.0

    Including only string columns in a ``DataFrame`` description.

    >>> df.describe(include=[object])  # doctest: +SKIP
           object
    count       3
    unique      3
    top         a
    freq        1

    Including only categorical columns from a ``DataFrame`` description.

    >>> df.describe(include=['category'])
           categorical
    count            3
    unique           3
    top              d
    freq             1

    Excluding numeric columns from a ``DataFrame`` description.

    >>> df.describe(exclude=[np.number])  # doctest: +SKIP
           categorical object
    count            3      3
    unique           3      3
    top              f      a
    freq             1      1

    Excluding object columns from a ``DataFrame`` description.

    >>> df.describe(exclude=[object])  # doctest: +SKIP
           categorical  numeric
    count            3      3.0
    unique           3      NaN
    top              f      NaN
    freq             1      NaN
    mean           NaN      2.0
    std            NaN      1.0
    min            NaN      1.0
    25%            NaN      1.5
    50%            NaN      2.0
    75%            NaN      2.5
    max            NaN      3.0

In [69]:
Municipios.describe() # Analisis descriptivo para columnas cuantitativas

       Superficie    Poblacion   Irural  denspobl
count    1,117.00     1,118.00 1,118.00  1,117.00
mean     1,020.43    44,095.63    46.78    165.34
std      3,217.70   260,344.32    12.70    733.12
min         15.84       288.00     0.00      0.07
25%        132.76     6,614.00    40.00     21.43
50%        287.04    12,796.50    46.00     44.89
75%        704.10    27,501.75    52.00     93.37
max     65,597.21 7,592,871.00   100.00 14,442.77

In [70]:
Municipios.describe(percentiles=[0.1,0.25,0.5,0.75,0.9])

       Superficie    Poblacion   Irural  denspobl
count    1,117.00     1,118.00 1,118.00  1,117.00
mean     1,020.43    44,095.63    46.78    165.34
std      3,217.70   260,344.32    12.70    733.12
min         15.84       288.00     0.00      0.07
10%         72.57     3,584.40    34.00      9.41
25%        132.76     6,614.00    40.00     21.43
50%        287.04    12,796.50    46.00     44.89
75%        704.10    27,501.75    52.00     93.37
90%      1,643.21    58,227.60    59.00    225.25
max     65,597.21 7,592,871.00   100.00 14,442.77

In [71]:
Municipios.describe(include="object") # Analisis descriptivo para columnas cualitativas

,Departamento,Dep,Municipio,Depmun,Region,Tipo,Zona,Municipio2
count,1118,1118,1118,1118,1118,1118,1118,1118
unique,33,33,1030,1118,6,2,2,1030
top,Antioquia,05,Villanueva,05001,Centro Oriente,Otros,Rural,villanueva
freq,125,125,4,1,367,1085,822,4

<h1 style="color:red;"> Ejemplo 2 </h1>
Cálculo de algunas estadísticas descriptivas (personalizadas) para las variables numéricas en el conjunto de datos Municipios.

In [1]:
# Crea un sumary para estadisticas descriptivas

def summary(y,include='numeric'):
    def numer(x):
        x2 = x.dropna() # Quita los NA
        a = x.isna().sum() # Suna la cantidad de NA que hay
        b = x2.mean() # Media
        c = x2.std() # Desviacion estandar
        d = c/b # Coeficiente de variacaion
        e = x2.skew() 
        f = x2.kurt()
        g = x2.min() # Minino
        h = np.quantile(x2,0.25)
        i = x2.median()
        j = np.quantile(x2,0.75)
        k = x2.max() # Maxino
        m = x2.max() - x2.min()
        n = j - h
        l = pd.Series({"Missings":a,"Mean":b,"St.dev":c,"Coef.var":d,"Skewness":e,
                       "Kurtosis":f,"Min":g,"%25":h,"Median":i,"%75":j,"Max":k,"Rango":m, "RIQ":n})
        return(l)
    if include == 'numeric': 
        numerics = y.select_dtypes(include='number')
        if len(numerics.columns) > 0: return(numerics.apply(numer)) 
        else: print('Error. There are not numeric-type columns!!')
    if include == 'object':    
        objects = y.select_dtypes(include='object')
        if len(objects.columns) > 0: return(objects.describe(include="object"))
        else: print('Error. There are not object-type columns!!')

In [6]:
summary(Municipios,include="numeric")

          Superficie    Poblacion  Irural  denspobl
Missings        1.00         0.00    0.00      1.00
Mean        1,020.43    44,095.63   46.78    165.34
St.dev      3,217.70   260,344.32   12.70    733.12
Coef.var        3.15         5.90    0.27      4.43
Skewness       10.85        23.38    0.70     12.33
Kurtosis      174.83       645.49    3.34    190.09
Min            15.84       288.00    0.00      0.07
%25           132.76     6,614.00   40.00     21.43
Median        287.04    12,796.50   46.00     44.89
%75           704.10    27,501.75   52.00     93.37
Max        65,597.21 7,592,871.00  100.00 14,442.77
Rango      65,581.38 7,592,583.00  100.00 14,442.70
RIQ           571.34    20,887.75   12.00     71.94

In [74]:
summary(Municipios,include="object")

,Departamento,Dep,Municipio,Depmun,Region,Tipo,Zona,Municipio2
count,1118,1118,1118,1118,1118,1118,1118,1118
unique,33,33,1030,1118,6,2,2,1030
top,Antioquia,05,Villanueva,05001,Centro Oriente,Otros,Rural,villanueva
freq,125,125,4,1,367,1085,822,4

<center><h1 style="color:red;"> Exportación de datos   </h1></center>
Guardando el conjunto de datos Municipios en el directorio de trabajo para su uso posterior.

In [75]:
Municipios.to_pickle("Municipios.pkl")
del Municipios

In [43]:
Municipios = pd.read_pickle("Municipios.pkl")
Municipios.info()
Municipios.head(15)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1118 entries, 0 to 1117
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Departamento  1118 non-null   object
 1   Dep           1118 non-null   object
 2   Municipio     1118 non-null   object
 3   Depmun        1118 non-null   object
 4   Superficie    1117 non-null   float64
 5   Poblacion     1118 non-null   float64
 6   Irural        1118 non-null   float64
 7   Region        1118 non-null   object
 8   Tipo          1118 non-null   object
 9   denspobl      1117 non-null   float64
 10  Zona          1118 non-null   object
 11  Municipio2    1118 non-null   object
 12  Iguales       1118 non-null   bool
dtypes: bool(1), float64(4), object(8)
memory usage: 106.0+ KB

,Departamento,Dep,Municipio,Depmun,Superficie,Poblacion,Irural,Region,Tipo,denspobl,Zona,Municipio2,Iguales
0,Antioquia,05,Medellín,05001,374.83,"2,483,545.00",5.00,Eje Cafetero,Capital,"6,625.78",Urbano,medellin,False
1,Antioquia,05,Abejorral,05002,507.13,"20,258.00",45.00,Eje Cafetero,Otros,39.95,Rural,abejorral,False
2,Antioquia,05,Abriaquí,05004,296.96,"2,710.00",58.00,Eje Cafetero,Otros,9.13,Rural,abriaqui,False
3,Antioquia,05,Alejandría,05021,128.93,"4,669.00",48.00,Eje Cafetero,Otros,36.21,Rural,alejandria,True
4,Antioquia,05,Amagá,05030,84.13,"30,777.00",28.00,Eje Cafetero,Otros,365.82,Urbano,amaga,True
5,Antioquia,05,Amalfi,05031,"1,209.13","26,552.00",54.00,Eje Cafetero,Otros,21.96,Rural,amalfi,False
6,Antioquia,05,Andes,05034,402.50,"43,713.00",38.00,Eje Cafetero,Otros,108.60,Urbano,andes,False
7,Antioquia,05,Angelópolis,05036,81.88,"5,790.00",37.00,Eje Cafetero,Otros,70.72,Urbano,angelopolis,False
8,Antioquia,05,Angostura,05038,338.67,"11,462.00",47.00,Eje Cafetero,Otros,33.84,Rural,angostura,True
9,Antioquia,05,Anorí,05040,"1,413.77","18,737.00",58.00,Eje Cafetero,Otros,13.25,Rural,anori,False
10,Antioquia,05,Santafé De Antioquia,05042,525.60,"26,598.00",45.00,Eje Cafetero,Otros,50.60,Rural,santafe de antioquia,False
11,Antioquia,05,Anza,05044,255.92,"7,085.00",48.00,Eje Cafetero,Otros,27.68,Rural,anza,True
12,Antioquia,05,Apartadó,05045,535.17,"124,647.00",34.00,Eje Cafetero,Otros,232.91,Urbano,apartado,False
13,Antioquia,05,Arboletes,05051,754.25,"29,942.00",48.00,Eje Cafetero,Otros,39.70,Rural,arboletes,False
14,Antioquia,05,Argelia,05055,245.34,"7,577.00",46.00,Eje Cafetero,Otros,30.88,Rural,argelia,True

In [77]:
Municipios.to_csv("Munis.csv",sep=";",index=False,encoding="utf-8")
Municipios.to_excel("Munis.xlsx",index=False)

 <center><h1 style="color:red;"> Tablas de frecuencias   </h1></center>

In [78]:
from mismacrospython import onewayfreq, twowayfreq # TRAE LAS FUNCIONES  onewayfreq, twowayfreq QUE ESTAN EN mismacrospython (mismacrospython es del profe)
help(pd.crosstab)

Help on function crosstab in module pandas.core.reshape.pivot:

crosstab(index, columns, values=None, rownames=None, colnames=None, aggfunc=None, margins: 'bool' = False, margins_name: 'str' = 'All', dropna: 'bool' = True, normalize=False) -> 'DataFrame'
    Compute a simple cross tabulation of two (or more) factors. By default
    computes a frequency table of the factors unless an array of values and an
    aggregation function are passed.

    Parameters
    ----------
    index : array-like, Series, or list of arrays/Series
        Values to group by in the rows.
    columns : array-like, Series, or list of arrays/Series
        Values to group by in the columns.
    values : array-like, optional
        Array of values to aggregate according to the factors.
        Requires `aggfunc` be specified.
    rownames : sequence, default None
        If passed, must match number of row arrays passed.
    colnames : sequence, default None
        If passed, must match number of column arrays passed.
    aggfunc : function, optional
        If specified, requires `values` be specified as well.
    margins : bool, default False
        Add row/column margins (subtotals).
    margins_name : str, default 'All'
        Name of the row/column that will contain the totals
        when margins is True.
    dropna : bool, default True
        Do not include columns whose entries are all NaN.
    normalize : bool, {'all', 'index', 'columns'}, or {0,1}, default False
        Normalize by dividing all values by the sum of values.

        - If passed 'all' or `True`, will normalize over all values.
        - If passed 'index' will normalize over each row.
        - If passed 'columns' will normalize over each column.
        - If margins is `True`, will also normalize margin values.

    Returns
    -------
    DataFrame
        Cross tabulation of the data.

    See Also
    --------
    DataFrame.pivot : Reshape data based on column values.
    pivot_table : Create a pivot table as a DataFrame.

    Notes
    -----
    Any Series passed will have their name attributes used unless row or column
    names for the cross-tabulation are specified.

    Any input passed containing Categorical data will have **all** of its
    categories included in the cross-tabulation, even if the actual data does
    not contain any instances of a particular category.

    In the event that there aren't overlapping indexes an empty DataFrame will
    be returned.

    Reference :ref:`the user guide <reshaping.crosstabulations>` for more examples.

    Examples
    --------
    >>> a = np.array(["foo", "foo", "foo", "foo", "bar", "bar",
    ...               "bar", "bar", "foo", "foo", "foo"], dtype=object)
    >>> b = np.array(["one", "one", "one", "two", "one", "one",
    ...               "one", "two", "two", "two", "one"], dtype=object)
    >>> c = np.array(["dull", "dull", "shiny", "dull", "dull", "shiny",
    ...               "shiny", "dull", "shiny", "shiny", "shiny"],
    ...              dtype=object)
    >>> pd.crosstab(a, [b, c], rownames=['a'], colnames=['b', 'c'])
    b   one        two
    c   dull shiny dull shiny
    a
    bar    1     2    1     0
    foo    2     2    1     2

    Here 'c' and 'f' are not represented in the data and will not be
    shown in the output because dropna is True by default. Set
    dropna=False to preserve categories with no data.

    >>> foo = pd.Categorical(['a', 'b'], categories=['a', 'b', 'c'])
    >>> bar = pd.Categorical(['d', 'e'], categories=['d', 'e', 'f'])
    >>> pd.crosstab(foo, bar)
    col_0  d  e
    row_0
    a      1  0
    b      0  1
    >>> pd.crosstab(foo, bar, dropna=False)
    col_0  d  e  f
    row_0
    a      1  0  0
    b      0  1  0
    c      0  0  0

<h1 style="color:red;"> Ejemplo 1 </h1>
Qué porcentaje del total representan los municipios de la región Caribe? Cuantos municipios tiene la región Pacífico? Cuales son las 2 regiones con mayor número de municipios? Qué porcentaje del total representan los municipios de estas 2 regiones? Qué porcentaje de los municipios son rurales?

In [79]:
# con onewayfreq
onewayfreq(rows="Region",data=Municipios,ord="freq")

           Region  Frequency  Percent  CumulativeFrequency  CumulativePercent
0  Centro Oriente        367    32.83                  367              32.83
1          Caribe        194    17.35                  561              50.18
2    Eje Cafetero        178    15.92                  739              66.10
3        Pacífico        177    15.83                  916              81.93
4      Centro Sur        124    11.09                 1040              93.02
5           Llano         78     6.98                 1118             100.00

In [80]:
# con pandas
(pd.crosstab(Municipios.Region,"Result",colnames=" ")
   .sort_values("Result",ascending=False))

                Result
Region
Centro Oriente     367
Caribe             194
Eje Cafetero       178
Pacífico           177
Centro Sur         124
Llano               78

In [81]:
# Con onewayfreq
onewayfreq(rows="Zona",data=Municipios,ord="level",cum=False)

     Zona  Frequency  Percent
0   Rural        822    73.52
1  Urbano        296    26.48

In [82]:
# con pandas
(pd.crosstab(Municipios.Zona,"Result",colnames=" ")
   .sort_values("Zona",ascending=True))

        Result
Zona
Rural      822
Urbano     296

<h1 style="color:red;"> Ejemplo 2 </h1>
Qué porcentaje de la población habita en la región Centro Oriente? Cuantos habitantes tiene la región Centro Sur? Cuales son las 2 regiones con mayor número de habitantes? Qué porcentaje de la población habita en estas 2 regiones?

In [83]:
onewayfreq(rows="Region",weight="Poblacion",data=Municipios,ord="-freq")

,Region,Frequency,Percent,CumulativeFrequency,CumulativePercent
0,Llano,"2,048,306.00",4.15,"2,048,306.00",4.15
1,Centro Sur,"3,284,811.00",6.66,"5,333,117.00",10.82
2,Pacífico,"8,134,239.00",16.50,"13,467,356.00",27.32
3,Eje Cafetero,"9,058,916.00",18.38,"22,526,272.00",45.69
4,Caribe,"11,060,389.00",22.44,"33,586,661.00",68.13
5,Centro Oriente,"15,712,252.00",31.87,"49,298,913.00",100.00

In [84]:
(pd.crosstab(Municipios.Region,"Result",values=Municipios.Poblacion,aggfunc=sum,colnames=" ")
   .sort_values("Result",ascending=True))

                      Result
Region
Llano           2,048,306.00
Centro Sur      3,284,811.00
Pacífico        8,134,239.00
Eje Cafetero    9,058,916.00
Caribe         11,060,389.00
Centro Oriente 15,712,252.00

In [85]:
onewayfreq(rows="Zona",weight="Poblacion",data=Municipios,cum=False)

     Zona     Frequency  Percent
0   Rural 14,152,533.00    28.71
1  Urbano 35,146,380.00    71.29

In [86]:
(pd.crosstab(Municipios.Zona,"Result",values=Municipios.Poblacion,aggfunc=sum,colnames=" ")
   .sort_values("Zona",ascending=True))

              Result
Zona
Rural  14,152,533.00
Urbano 35,146,380.00

<h1 style="color:red;"> Ejemplo 3 </h1>
Cuales son los 2 departamentos más/menos poblados de la región Pacífico? Qué porcentaje representan estos municipios del total de la población en la región? Qué porcentaje de la población de la región Caribe habita en municipios rurales?

In [87]:
p1 = onewayfreq(rows="Departamento",weight="Poblacion",data=Municipios,subset="Region=='Pacífico'",ord="freq")

In [99]:
p1

,Departamento,Frequency,Percent,CumulativeFrequency,CumulativePercent
0,Valle Del Cauca,"4,506,768.00",55.40,"4,506,768.00",55.40
1,Nariño,"1,628,981.00",20.03,"6,135,749.00",75.43
2,Cauca,"1,458,557.00",17.93,"7,594,306.00",93.36
3,Chocó,"539,933.00",6.64,"8,134,239.00",100.00

In [100]:
Pacifico = Municipios.query("Region=='Pacífico'")
(pd.crosstab(Pacifico.Departamento,"Result",values=Pacifico.Poblacion,aggfunc=sum,colnames=" ")
   .sort_values("Result",ascending=False))

                      Result
Departamento
Valle Del Cauca 4,506,768.00
Nariño          1,628,981.00
Cauca           1,458,557.00
Chocó             539,933.00

In [89]:
onewayfreq(rows="Zona",weight="Poblacion",data=Municipios,subset="Region=='Caribe'",cum=False)

     Zona    Frequency  Percent
0   Rural 4,300,236.00    38.88
1  Urbano 6,760,153.00    61.12

In [90]:
Caribe = Municipios.query("Region=='Caribe'")
(pd.crosstab(Caribe.Zona,"Result",values=Caribe.Poblacion,aggfunc=sum,colnames=" ")
   .sort_values("Result",ascending=True))

             Result
Zona
Rural  4,300,236.00
Urbano 6,760,153.00

<h1 style="color:red;"> Ejemplo 4 </h1>
Qué porcentaje de la superficie total de Colombia representa la región Llano? Cual es la superficie de la región Centro Oriente? Cuales son las 2 regiones con mayor/menor superficie? Qué porcentaje representan estas 2 regiones de la superficie total de Colombia? Qué porcentaje de la superficie del país ocupan los municipios rurales?

In [91]:
onewayfreq(rows="Region",weight="Superficie",data=Municipios,ord="freq")

           Region  Frequency  Percent  CumulativeFrequency  CumulativePercent
0           Llano 434,000.02    38.08           434,000.02              38.08
1      Centro Sur 267,857.41    23.50           701,857.43              61.58
2        Pacífico 131,660.39    11.55           833,517.82              73.13
3          Caribe 131,034.59    11.50           964,552.41              84.62
4  Centro Oriente  99,549.64     8.73         1,064,102.05              93.36
5    Eje Cafetero  75,720.28     6.64         1,139,822.33             100.00

In [92]:
(pd.crosstab(Municipios.Region,"Result",values=Municipios.Superficie,aggfunc=sum,colnames=" ")
   .sort_values("Result",ascending=False))

                   Result
Region
Llano          434,000.02
Centro Sur     267,857.41
Pacífico       131,660.39
Caribe         131,034.59
Centro Oriente  99,549.64
Eje Cafetero    75,720.28

In [93]:
onewayfreq(rows="Region",weight="Superficie",data=Municipios,ord="-freq")

           Region  Frequency  Percent  CumulativeFrequency  CumulativePercent
0    Eje Cafetero  75,720.28     6.64            75,720.28               6.64
1  Centro Oriente  99,549.64     8.73           175,269.92              15.38
2          Caribe 131,034.59    11.50           306,304.51              26.87
3        Pacífico 131,660.39    11.55           437,964.89              38.42
4      Centro Sur 267,857.41    23.50           705,822.30              61.92
5           Llano 434,000.02    38.08         1,139,822.33             100.00

In [94]:
(pd.crosstab(Municipios.Region,"Result",values=Municipios.Superficie,aggfunc=sum,colnames=" ")
   .sort_values("Result",ascending=True))

                   Result
Region
Eje Cafetero    75,720.28
Centro Oriente  99,549.64
Caribe         131,034.59
Pacífico       131,660.39
Centro Sur     267,857.41
Llano          434,000.02

In [95]:
onewayfreq(rows="Zona",weight="Superficie",data=Municipios,ord="freq",cum=False)

     Zona    Frequency  Percent
0   Rural 1,064,081.77    93.36
1  Urbano    75,740.56     6.64

<h1 style="color:red;"> Ejemplo 5 </h1>
Qué porcentaje de los municipios de la región Llano son rurales? Qué porcentaje de los municipios rurales están en la región Pacífico?

In [96]:
twowayfreq(rows="Region",columns="Zona",data=Municipios,ord="freq",rowpercent=True,colpercent=True)

Frequency
Row percent
Col percent

   Region  /  Zona  Rural  Urbano    Total

0   Centro Oriente 273.00   94.00   367.00
1                   74.39   25.61   100.00
2                   33.21   31.76    32.83
3           Caribe 140.00   54.00   194.00
4                   72.16   27.84   100.00
5                   17.03   18.24    17.35
6     Eje Cafetero 102.00   76.00   178.00
7                   57.30   42.70   100.00
8                   12.41   25.68    15.92
9         Pacífico 121.00   56.00   177.00
10                  68.36   31.64   100.00
11                  14.72   18.92    15.83
12      Centro Sur 110.00   14.00   124.00
13                  88.71   11.29   100.00
14                  13.38    4.73    11.09
15           Llano  76.00    2.00    78.00
16                  97.44    2.56   100.00
17                   9.25    0.68     6.98
18           Total 822.00  296.00 1,118.00
19                  73.52   26.48   100.00
20                 100.00  100.00   100.00

In [97]:
pd.crosstab(Municipios.Region,Municipios.Zona)

Zona            Rural  Urbano
Region
Caribe            140      54
Centro Oriente    273      94
Centro Sur        110      14
Eje Cafetero      102      76
Llano              76       2
Pacífico          121      56

 <center><h1 style="color:red;"> Consulta, transformación, y creación de conjuntos de datos   </h1></center>

 <center><h1 style="color:blue;">Libreria duckdb</h1></center>

In [105]:
!pip install duckdb
import duckdb
con = duckdb.connect(database=':memory:')

Requirement already satisfied: duckdb in c:\users\labau\anaconda3\lib\site-packages (1.2.0)

In [106]:
E1 = con.execute("""select   Departamento, Dep, Depmun, Municipio, Superficie, Poblacion
                    from     Municipios
                    where    Dep in ('05','17') and Poblacion > 20000
                    order by Dep asc, Poblacion desc""").df()
E1.info()
E1.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Departamento  66 non-null     object
 1   Dep           66 non-null     object
 2   Depmun        66 non-null     object
 3   Municipio     66 non-null     object
 4   Superficie    66 non-null     float64
 5   Poblacion     66 non-null     float64
dtypes: float64(2), object(4)
memory usage: 3.2+ KB

  Departamento Dep Depmun Municipio  Superficie    Poblacion
0    Antioquia  05  05001  Medellín      374.83 2,483,545.00
1    Antioquia  05  05088     Bello      147.76   538,527.00
2    Antioquia  05  05360    Itagui       19.65   283,794.00
3    Antioquia  05  05266  Envigado       78.00   236,114.00
4    Antioquia  05  05615  Rionegro      195.94   139,553.00
5    Antioquia  05  05837     Turbo    2,919.54   127,565.00
6    Antioquia  05  05045  Apartadó      535.17   124,647.00
7    Antioquia  05  05154  Caucasia    1,429.12    93,044.00
8    Antioquia  05  05631  Sabaneta       15.84    85,484.00
9    Antioquia  05  05129    Caldas      132.76    81,658.00

In [107]:
E2 = con.execute("""select   Departamento, Dep, Depmun, Municipio, Superficie,
                             Poblacion, case when denspobl <= 30 then 'Baja'
                                             when denspobl > 85 then 'Alta'
                                             else 'Media'
                                        end as denspoblC
                    from     Municipios
                    where    Dep not in ('15','68') and Superficie < 300
                    order by Dep asc, Poblacion desc""").df()

E2.info()
E1.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 412 entries, 0 to 411
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Departamento  412 non-null    object
 1   Dep           412 non-null    object
 2   Depmun        412 non-null    object
 3   Municipio     412 non-null    object
 4   Superficie    412 non-null    float64
 5   Poblacion     412 non-null    float64
 6   denspoblC     412 non-null    object
dtypes: float64(2), object(5)
memory usage: 22.7+ KB

  Departamento Dep Depmun Municipio  Superficie    Poblacion
0    Antioquia  05  05001  Medellín      374.83 2,483,545.00
1    Antioquia  05  05088     Bello      147.76   538,527.00
2    Antioquia  05  05360    Itagui       19.65   283,794.00
3    Antioquia  05  05266  Envigado       78.00   236,114.00
4    Antioquia  05  05615  Rionegro      195.94   139,553.00
5    Antioquia  05  05837     Turbo    2,919.54   127,565.00
6    Antioquia  05  05045  Apartadó      535.17   124,647.00
7    Antioquia  05  05154  Caucasia    1,429.12    93,044.00
8    Antioquia  05  05631  Sabaneta       15.84    85,484.00
9    Antioquia  05  05129    Caldas      132.76    81,658.00

In [108]:
con.execute("""select   Depmun, count(*) as count
               from     Municipios
               group by Depmun 
               having   count > 1""").df()

Empty DataFrame
Columns: [Depmun, count]
Index: []

 <center><h1 style="color:red;"> Consulta, transformación, y creación de conjuntos de datos </h1></center>
  <center><h1 style="color:blue;">Libreria pandas</h1></center>

<h1 style="color:red;"> Ejemplo 1 </h1>
Conjunto de datos con las variables Departamento, Dep, Depmun, Municipio, Superficie y Poblacion que incluye todos los municipios de los departamentos de Antioquia y Caldas con más de 20 mil habitantes y donde los mismos están ordenados con respecto a Dep y de mayor a menor con respecto a Poblacion.

In [47]:
e1 = (Municipios
      .loc[:,["Departamento","Dep","Depmun","Municipio","Superficie","Poblacion"]] #
      .query("Poblacion > 20000 & Dep in ('05','17')")
      .sort_values(by=["Dep","Poblacion"],ascending=[True,False]).reset_index(drop=True)
     )

# .loc[:,] = se usa para acceder a un subconjunto de filas y columnas del DataFrame. (los : indica que queremos todas la filas)
# .query = filtra las filas del DataFrame según una condición.
# .sort_values = ordena el DataFrame.
# .reset_index = restablece los índices del DataFrame.
e1.info()
e1.head(60)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Departamento  66 non-null     object
 1   Dep           66 non-null     object
 2   Depmun        66 non-null     object
 3   Municipio     66 non-null     object
 4   Superficie    66 non-null     float64
 5   Poblacion     66 non-null     float64
dtypes: float64(2), object(4)
memory usage: 3.2+ KB

   Departamento Dep   Depmun             Municipio  Superficie    Poblacion
0     Antioquia  05    05001              Medellín      374.83 2,483,545.00
1     Antioquia  05    05088                 Bello      147.76   538,527.00
2     Antioquia  05    05360                Itagui       19.65   283,794.00
3     Antioquia  05    05266              Envigado       78.00   236,114.00
4     Antioquia  05    05615              Rionegro      195.94   139,553.00
5     Antioquia  05    05837                 Turbo    2,919.54   127,565.00
6     Antioquia  05    05045              Apartadó      535.17   124,647.00
7     Antioquia  05    05154              Caucasia    1,429.12    93,044.00
8     Antioquia  05    05631              Sabaneta       15.84    85,484.00
9     Antioquia  05    05129                Caldas      132.76    81,658.00
10    Antioquia  05    05212            Copacabana       67.76    80,000.00
11    Antioquia  05    05380           La Estrella       36.63    73,696.00
12    Antioquia  05    05376               La Ceja      132.71    66,746.00
13    Antioquia  05    05440             Marinilla      114.87    66,399.00
14    Antioquia  05    05148  El Carmen De Viboral      423.65    61,122.00
15    Antioquia  05    05172             Chigorodó      721.68    58,684.00
16    Antioquia  05    05318                Guarne      151.81    56,774.00
17    Antioquia  05    05079               Barbosa      205.67    53,242.00
18    Antioquia  05    05308             Girardota       82.86    53,162.00
19    Antioquia  05    05250              El Bagre    1,560.25    52,925.00
20    Antioquia  05    05147                Carepa      387.27    49,659.00
21    Antioquia  05    05034                 Andes      402.50    43,713.00
22    Antioquia  05    05490               Necoclí    1,255.54    43,257.00
23    Antioquia  05    05887               Yarumal      738.26    42,116.00
24    Antioquia  05    05579         Puerto Berrío    1,220.11    40,048.00
25    Antioquia  05    05736               Segovia    1,127.33    38,692.00
26    Antioquia  05    05686    Santa Rosa De Osos      864.78    37,143.00
27    Antioquia  05    05756                Sonsón    1,346.40    36,394.00
28    Antioquia  05    05697          El Santuario       83.45    36,043.00
29    Antioquia  05    05665    San Pedro De Uraba      602.53    31,571.00
30    Antioquia  05    05030                 Amagá       84.13    30,777.00
31    Antioquia  05    05847                 Urrao    2,563.40    30,484.00
32    Antioquia  05    05051             Arboletes      754.25    29,942.00
33    Antioquia  05    05120               Cáceres    1,873.80    29,716.00
34    Antioquia  05    05604              Remedios    1,989.19    29,061.00
35    Antioquia  05    05790                Tarazá    1,148.98    27,517.00
36    Antioquia  05    05361               Ituango    2,841.12    27,419.00
37    Antioquia  05    05679         Santa Bárbara      196.17    26,944.00
38    Antioquia  05    05495                 Nechí      937.32    26,652.00
39    Antioquia  05    05042  Santafé De Antioquia      525.60    26,598.00
40    Antioquia  05    05031                Amalfi    1,209.13    26,552.00
41    Antioquia  05    05101        Ciudad Bolívar      260.45    26,160.00
42    Antioquia  05    05895              Zaragoza    1,167.36    25,210.00
43    Antioquia  05    05282              Fredonia      258.09    24,553.00
44    Antioquia  05    05607                Retiro      243.60    24,185.00
45    Antioquia  05    05234               Dabeiba    1,957.26    23,255.00
46    Antioquia  05    05890               Yolombó    1,012.51    23,050.00
47    Antioquia  05    05664             San Pedro      220.94    22,447.00
48    Antioquia  05    05674           San Vicente      230.49    22,258.00
49    Antioquia  05    05400              La Unión      167.74    21,963.00
50    Antioquia  05    05670             San Roque      424.85    21,533.00
51    Antioquia  05    05209             Concordia      247.88    21,504.00
52    Antioquia  05    05541                 Peñol      118.31    21,427.00
53    Antioquia  05    05284              Frontino    1,384.13    20,657.00
54    Antioquia  05    05659     San Juan De Urabá      252.00    20,549.00
55    Antioquia  05    05002             Abejorral      507.13    20,258.00
56       Caldas  17  17001.0             Manizales      441.00   440,608.00
57       Caldas  17  17380.0             La Dorada      549.24    72,972.00
58       Caldas  17  17873.0            Villamaría      455.07    66,189.00
59       Caldas  17  17174.0             Chinchiná      109.37    51,773.00

In [48]:
# Crea una funcion para comparar dos DataFrames
def comparacion(a,b):
    if len(a.select_dtypes(exclude='float').columns) > 0:
        Nf = a.select_dtypes(exclude='float').equals(b.select_dtypes(exclude='float'))
    else:
        Nf = True
    if len(a.select_dtypes(include='float').columns) > 0:
        f = a.select_dtypes(include='float').round(5).equals(b.select_dtypes(include='float').round(5))
    else:
        f = True
    if Nf==True & f==True:
        return(True)
    else:
        return(False)

In [49]:
comparacion(e1,E1)

NameError: name 'E1' is not defined

<h1 style="color:red;"> Ejemplo 2 </h1>

Conjunto de datos con las variables Departamento, Dep, Depmun, Municipio, Superficie y Poblacion que incluye todos los municipios con superficies menores a 300  km2 excepto los de Boyacá y Santander, y que están ordenados por Dep y de mayor a menor por Poblacion. Incluye una variable definida como "Baja" para los municipios con denspobl menor a 30, "Alta" para los municipios con denspobl mayor a 85, y "Media" para los demás.

In [113]:
e2 = Municipios
# Creando una variable e2 que es una copia del DataFrame Municipios.

e2["denspoblC"] = pd.cut(e2["denspobl"],[np.NINF,30,85,np.inf],labels=["Baja","Media","Alta"]).astype("object")
# e2["denspoblC"] = Crea una nueva columna llamada (denspoblC)
# pd.cut = es una función de pandas que se utiliza para segmentar y ordenar los datos en intervalos.
# e2["denspobl"] = es la columna del DataFrame que queremos segmentar.
# [np.NINF,30,85,np.inf] = son los límites de los intervalos:
#    np.NINF =  representa el límite inferior negativo infinito.
#    30 = es el límite superior del primer intervalo.
#    85 = es el límite superior del segundo intervalo.
#    np.inf =  representa el límite superior infinito.
# labels=["Baja","Media","Alta"] = son las etiquetas que queremos asignar a cada intervalo.
# astype("object") =  convierte los valores resultantes en el tipo de datos object.

e2 = (e2
      .loc[:,["Departamento","Dep","Depmun","Municipio","Superficie","Poblacion","denspoblC"]] 
      .query("Dep not in ('15','68') & Superficie < 300")
      .sort_values(by=["Dep","Poblacion"],ascending=[True,False])
      .reset_index(drop=True)
     )

e2.info()
e2.head(10)
comparacion(e2,E2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 412 entries, 0 to 411
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Departamento  412 non-null    object
 1   Dep           412 non-null    object
 2   Depmun        412 non-null    object
 3   Municipio     412 non-null    object
 4   Superficie    412 non-null    float64
 5   Poblacion     412 non-null    float64
 6   denspoblC     412 non-null    object
dtypes: float64(2), object(5)
memory usage: 22.7+ KB

True

<h1 style="color:red;"> Ejemplo 3 </h1>

Existen dos o más municipios con el mismo Depmun?

In [114]:
(Municipios
 .groupby("Depmun") 
 .agg(conteo=("Depmun","count")).reset_index()
 .query("conteo > 1")
)

# .groupby("Depmun") = Agrupa el DataFrame Municipios por la columna Depmun.
# .agg = Es una función de agregación que aplica operaciones a los grupos.
# .conteo=("Depmun","count") = crea una nueva columna llamada "conteo" que contiene el conteo de elementos en cada grupo Depmun.
# .query("conteo > 1") = Filtra el DataFrame resultante para mantener solo las filas donde el conteo es mayor que 1.

Empty DataFrame
Columns: [Depmun, conteo]
Index: []

<h1 style="color:red;"> Ejemplo 4 </h1>

De los departamentos con dos o más municipios cual es el menos homogeneo (de acuerdo al coeficiente de variación) con respecto a la superficie de los municipios que lo componen?

In [116]:
def cv(x): 
    return(x.std()/x.mean())
# Funcion para calcular el coeficiente de variacion


(Municipios
 .groupby(["Dep","Departamento"])
 .agg(conteo=("Depmun","count"),cv=("Superficie",cv)).reset_index()
 .query("conteo > 1")
 .drop(columns="conteo")  # Elimina la columna
 .sort_values(by=["cv"],ascending=False).reset_index(drop=True)
 .head(n=2) # Muetra solo los dos primeros
)

  Dep     Departamento   cv
0  18          Caquetá 1.94
1  76  Valle Del Cauca 1.93

<h1 style="color:red;"> Ejemplo 5 </h1>
De los departamentos con dos o más municipios cual es el más homogeneo (de acuerdo al coeficiente de variación) con respecto a la superficie de los municipios que lo componen?

In [117]:
(Municipios
 .groupby(["Dep","Departamento"])
 .agg(conteo=("Depmun","count"),cv=("Superficie",cv)).reset_index()
 .query("conteo > 1").drop(columns="conteo") 
 .sort_values(by=["cv"],ascending=True).reset_index(drop=True)
 .head(n=2)
)

  Dep Departamento   cv
0  88   San Andrés 0.14
1  95     Guaviare 0.14

<h1 style="color:red;"> Ejemplo 6 </h1>

Conjunto de datos con todos los departamentos, ordenados de mayor a menor con respecto a su población, que incluye la siguiente información: número de municipios, superficie, población, densidad poblacional, índice de ruralidad promedio ponderado por población, y una variable igual a "Grande" para los departamentos con población mayor a 1.5 millones de habitantes, "Pequeño" para departamentos con población menor a 300 mil habitantes, y "Mediano" para el resto.

In [118]:
def wtmean(x):
    w = Municipios.loc[x.index,"Poblacion"]
    return(sum(x*w)/sum(w))
# Crea una funcion para calcula la media ponderada de una variable x, utilizando los valores de la columna Poblacion del DataFrame Municipios como pesos.
# Cuando lo use: Tengo que cambiar la columna "Poblacion" par la que mesecite y espesifiar el DataFrame que este usando

def cases(x):
    out = "Mediano"
    if sum(x) < 300000:  out= "Pequeño"
    if sum(x) > 1500000: out= "Grande"
    return(out) 
# Crea una funcion para hacer las categorias e la funcion x
# Si la quiero usar solo tengo que modificar los nombres de las categorias y los interbalos

e6 = (Municipios
      .groupby(["Dep","Departamento"])
      .agg(nmunicipios=("Depmun","count"),
           totpob=("Poblacion","sum"),
           totsup=("Superficie","sum"),
           Irural=("Irural",wtmean),
           totpobC=("Poblacion",cases)).reset_index()
      .eval('''denspob = totpob/totsup''') # Crea una otra columna con los resultados de las anteriores
      .sort_values(by=["totpob"],ascending=False).reset_index(drop=True)
      .loc[:,["Dep","Departamento","nmunicipios","totpob","totsup","Irural","denspob","totpobC"]] # Indica que varibles quiero
     )

e6.info()
e6.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Dep           33 non-null     object
 1   Departamento  33 non-null     object
 2   nmunicipios   33 non-null     int64
 3   totpob        33 non-null     float64
 4   totsup        33 non-null     float64
 5   Irural        33 non-null     float64
 6   denspob       33 non-null     float64
 7   totpobC       33 non-null     object
dtypes: float64(4), int64(1), object(3)
memory usage: 2.2+ KB

,Dep,Departamento,nmunicipios,totpob,totsup,Irural,denspob,totpobC
0,11,Bogotá D C,1,"7,592,871.00","1,622.85",6.00,"4,678.72",Grande
1,05,Antioquia,125,"6,550,206.00","62,804.71",21.32,104.29,Grande
2,76,Valle Del Cauca,42,"4,506,768.00","20,665.54",22.58,218.08,Grande
3,25,Cundinamarca,116,"3,085,522.00","22,370.49",26.53,137.93,Grande
4,08,Atlántico,23,"2,638,151.00","3,315.75",10.93,795.64,Grande

<h1 style="color:red;"> Ejemplo 7 </h1>
Cual es la región con la mayor superficie?

In [119]:
(Municipios
 .groupby(["Region"])
 .agg(Superficie=("Superficie","sum")).reset_index()
 .sort_values(by=["Superficie"],ascending=False).reset_index(drop=True)
 .head(n=1)
)

  Region  Superficie
0  Llano  434,000.02

<h1 style="color:red;"> Ejemplo 8 </h1>
Conjunto de datos con todos los departamentos, ordenados de mayor a menor con respecto a su población, que incluye la siguiente información: número de municipios, superficie, población, densidad poblacional, todo referente a los municipios con índice de ruralidad mayor a 60.

In [12]:
e8 = (Municipios
      .query("Irural > 60")
      .groupby(["Dep","Departamento"])
      .agg(nmunicipios=("Depmun","count"),
           totpob=("Poblacion","sum"),
           totsup=("Superficie","sum")).reset_index()
      .sort_values(by=["totpob"],ascending=False).reset_index(drop=True)
      .eval('''denspob=totpob/totsup''')
     )


e8.info()
e8.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Dep           17 non-null     object
 1   Departamento  17 non-null     object
 2   nmunicipios   17 non-null     int64
 3   totpob        17 non-null     float64
 4   totsup        17 non-null     float64
 5   denspob       17 non-null     float64
dtypes: float64(3), int64(1), object(2)
memory usage: 944.0+ bytes

  Dep Departamento  nmunicipios     totpob     totsup  denspob
0  50         Meta           12 207,857.00  74,457.93     2.79
1  27        Chocó            8 153,096.00  26,448.17     5.79
2  85     Casanare           12 146,548.00  37,493.09     3.91
3  18      Caquetá            6 133,736.00  78,392.49     1.71
4  99      Vichada            4 110,599.00 100,063.37     1.11
5  95     Guaviare            4  84,716.00  55,575.23     1.52
6  91     Amazonas           11  77,753.00 109,497.05     0.71
7  86     Putumayo            2  65,053.00  15,483.47     4.20
8  81       Arauca            3  55,471.00  12,912.74     4.30
9  94      Guainía            9  49,473.00  71,289.35     0.69

<h1 style="color:red;"> Ejemplo 9 </h1>

Cual es la región con el mayor número de departamentos?

In [122]:
(Municipios
 .groupby(["Region"])
 .agg(Departamentos=("Dep","nunique")).reset_index() # Paracontar los departamentos
 .sort_values(by=["Departamentos"],ascending=[False])
)

           Region  Departamentos
0          Caribe              8
4           Llano              7
1  Centro Oriente              5
2      Centro Sur              5
3    Eje Cafetero              4
5        Pacífico              4

<h1 style="color:red;"> Ejemplo 10 </h1>

Conjunto de datos con todos los departamentos con al menos 650 mil habitantes y al menos 10 mil  km2 de superficie, ordenados de mayor a menor con relación a su densidad poblacional, y que incluye la siguiente información: número de municipios, superficie, población y densidad poblacional.

In [126]:
e10 = (Municipios
      .groupby(["Dep","Departamento"])
      .agg(nmunicipios=("Depmun","count"),
           totpob=("Poblacion","sum"),
           totsup=("Superficie","sum")).reset_index()
      .eval('''denspob=totpob/totsup''')
      .query("totpob >= 650000 & totsup >= 10000 " )
      .sort_values(by=["denspob"],ascending=False).reset_index(drop=True)
      .loc[:,["Dep","Departamento","totpob","totsup","denspob"]]
     )

e10.head()

  Dep     Departamento       totpob    totsup  denspob
0  76  Valle Del Cauca 4,506,768.00 20,665.54   218.08
1  25     Cundinamarca 3,085,522.00 22,370.49   137.93
2  05        Antioquia 6,550,206.00 62,804.71   104.29
3  70            Sucre   928,984.00 10,591.85    87.71
4  13          Bolívar 2,120,925.00 26,302.81    80.63

<h1 style="color:red;"> Ejemplo 11 </h1>

Conjunto de datos con todos los departamentos con al menos 650 mil habitantes y al menos 10 mil de superficie, ordenados de mayor a menor con relación a su densidad poblacional, y que incluye la siguiente información: número de municipios, superficie, población, y densidad poblacional, todo referente a municipios con índice de ruralidad mayor a 40.

In [127]:
e10 = (Municipios
      .query("Irural > 40 " )
      .groupby(["Dep","Departamento"])
      .agg(nmunicipios=("Depmun","count"),
           totpob=("Poblacion","sum"),
           totsup=("Superficie","sum")).reset_index()
      .eval('''denspob=totpob/totsup''')
      .query("totpob >= 650000 & totsup >= 10000 " )
      .sort_values(by=["denspob"],ascending=False).reset_index(drop=True)
      .loc[:,["Dep","Departamento","totpob","totsup","denspob"]]
     )

e10.head()

  Dep Departamento     totpob    totsup  denspob
0  44   La Guajira 927,506.00 20,621.96    44.98
1  23      Córdoba 813,722.00 18,777.92    43.33
2  20        Cesar 734,244.00 18,303.55    40.11
3  52       Nariño 757,725.00 25,475.11    29.74
4  13      Bolívar 653,793.00 22,520.49    29.03

<h1 style="color:red;"> Ejemplo 12 </h1>

Existen dos o más municipios con el mismo nombre? Cuantos? Cuales? En qué departamentos están ubicados?

In [130]:
Repetidos = (Municipios
             .groupby(["Municipio"])
             .agg(reps=("Municipio","count")).reset_index()
             .query("reps > 1")
             .sort_values(by=["reps"],ascending=[False]).reset_index(drop=True) 
            )
reps = Repetidos["Municipio"]
Repetidos.info()
Repetidos.head(10)


e12 = (Municipios
       .loc[:,["Municipio","Departamento","Dep","Depmun"]] 
       .query("Municipio in @reps")
       .sort_values(by=["Municipio","Departamento"],ascending=[True,True]).reset_index(drop=True)
      )

e12.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69 entries, 0 to 68
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Municipio  69 non-null     object
 1   reps       69 non-null     int64
dtypes: int64(1), object(1)
memory usage: 1.2+ KB

  Municipio     Departamento Dep   Depmun
0   Albania          Caquetá  18  18029.0
1   Albania       La Guajira  44  44035.0
2   Albania        Santander  68  68020.0
3     Albán     Cundinamarca  25  25019.0
4     Albán           Nariño  52  52019.0
5   Argelia        Antioquia  05    05055
6   Argelia            Cauca  19  19050.0
7   Argelia  Valle Del Cauca  76  76054.0
8   Armenia        Antioquia  05    05059
9   Armenia          Quindío  63  63001.0

<h1 style="color:red;"> Ejemplo 14 </h1>

Conjunto de datos con los municipios cuyos nombres inician con "A" o terminan con "o", no importa si llevan tilde o no.

In [131]:
e14 = (Municipios
       .query("Municipio.str.contains('^(A|Á)|(o|ó)$').values")
       .loc[:,["Dep","Departamento","Municipio","Depmun"]] 
       .sort_values(by=["Depmun"],ascending=[True]).reset_index(drop=True)
      )

e14.head(10)

  Dep Departamento    Municipio Depmun
0  05    Antioquia    Abejorral  05002
1  05    Antioquia     Abriaquí  05004
2  05    Antioquia   Alejandría  05021
3  05    Antioquia        Amagá  05030
4  05    Antioquia       Amalfi  05031
5  05    Antioquia        Andes  05034
6  05    Antioquia  Angelópolis  05036
7  05    Antioquia    Angostura  05038
8  05    Antioquia        Anorí  05040
9  05    Antioquia         Anza  05044

<h1 style="color:red;"> Ejemplo 15 </h1>

Conjunto de datos con los municipios cuyos nombres inician con "A" y terminan con "o", no importa si llevan tilde o no.

In [ ]:
e15 = (Municipios
       .query("Municipio.str.contains('^(A|Á).*(o|ó)$').values")
       .loc[:,["Dep","Departamento","Municipio","Depmun"]] 
       .sort_values(by=["Depmun"],ascending=[True]).reset_index(drop=True)
      )

e15.info()
e15.head(10)

<h1 style="color:red;"> Ejemplo 16 </h1>

Conjunto de datos con los municipios cuyo nombre tiene a la letra "e" en las posiciones 2 y 4, no importa si llevan tilde o no.

In [134]:
e16 = (Municipios
       .query("Municipio.str.contains('^.{1}(e|é).{1}(e|é).*').values")
       .loc[:,["Dep","Departamento","Municipio","Depmun"]] 
       .sort_values(by=["Depmun"],ascending=[True]).reset_index(drop=True)
      )

e16.info()
e16.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Dep           18 non-null     object
 1   Departamento  18 non-null     object
 2   Municipio     18 non-null     object
 3   Depmun        18 non-null     object
dtypes: object(4)
memory usage: 704.0+ bytes

  Dep Departamento               Municipio   Depmun
0  05    Antioquia                Medellín    05001
1  05    Antioquia                Remedios    05604
2  05    Antioquia                 Venecia    05861
3  08    Atlántico                 Repelón    08606
4  15       Boyacá                   Belén  15087.0
5  15       Boyacá               Betéitiva  15092.0
6  15       Boyacá                Jenesano  15367.0
7  18      Caquetá  Belén De Los Andaquies  18094.0
8  20        Cesar                Becerril  20045.0
9  23      Córdoba                  Cereté  23162.0

<h1 style="color:red;"> Ejemplo 17 </h1>
Conjunto de datos con los municipios cuyos nombres constan de más de una palabra.

In [135]:
e17 = (Municipios
       .query("Municipio.str.contains('.* .*').values")
       .loc[:,["Dep","Departamento","Municipio","Depmun"]] 
       .sort_values(by=["Depmun"],ascending=[True]).reset_index(drop=True)
      )

e17.info()
e17.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307 entries, 0 to 306
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Dep           307 non-null    object
 1   Departamento  307 non-null    object
 2   Municipio     307 non-null    object
 3   Depmun        307 non-null    object
dtypes: object(4)
memory usage: 9.7+ KB

  Dep Departamento             Municipio Depmun
0  05    Antioquia  Santafé De Antioquia  05042
1  05    Antioquia        Ciudad Bolívar  05101
2  05    Antioquia  El Carmen De Viboral  05148
3  05    Antioquia            Don Matías  05237
4  05    Antioquia              El Bagre  05250
5  05    Antioquia           Gómez Plata  05310
6  05    Antioquia               La Ceja  05376
7  05    Antioquia           La Estrella  05380
8  05    Antioquia            La Pintada  05390
9  05    Antioquia              La Unión  05400

<h1 style="color:red;"> Ejemplo 18 </h1>
Cuantos y cuales municipios tienen al menos una estación de monitoreo climático?

In [13]:
Estaciones = pd.read_excel("Estaciones.xlsx",dtype={'CODIGO': str, 'Depmun': str})
Estaciones.info()
Estaciones.head(20)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1968 entries, 0 to 1967
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   CODIGO     1968 non-null   object
 1   CAT        1968 non-null   object
 2   NOMBRE     1968 non-null   object
 3   ELEV       1968 non-null   int64
 4   longitud2  1968 non-null   object
 5   latitud2   1968 non-null   object
 6   PRECIP     1968 non-null   float64
 7   NDLL       1849 non-null   float64
 8   Depmun     1968 non-null   object
 9   longitud   1968 non-null   float64
 10  latitud    1956 non-null   float64
dtypes: float64(4), int64(1), object(6)
memory usage: 169.2+ KB

,CODIGO,CAT,NOMBRE,ELEV,longitud2,latitud2,PRECIP,NDLL,Depmun,longitud,latitud
0,26215010,CO,Concordia,2032,"75ø55'11""W","6ø2'23""N","2,234.71",211.20,05209,-75.92,6.04
1,26210080,PM,Herradura La,550,"75ø52'26,3""W","6ø5'57,2""N","1,897.48",118.70,05209,-75.87,6.10
2,27010650,PM,Don Matias,2200,"75ø24'0""W","6ø29'0""N","2,409.09",195.08,05237,-75.40,6.48
3,27010400,PM,Riogrande Almacen,2070,"75ø24'0""W","6ø33'0""N","3,195.15",224.22,05237,-75.40,6.55
4,27010440,PM,Riogrande Mocorong,1784,"75ø22'0""W","6ø33'0""N","3,589.65",230.06,05237,-75.37,6.55
5,27030060,PM,Amaceri,250,"74ø44'0""W","7ø45'0""N","4,373.90",170.52,05250,-74.73,7.75
6,27030050,PM,Bagre El,160,"74ø48'0""W","7ø37'0""N","4,481.06",151.52,05250,-74.80,7.62
7,23080650,PM,Campoalegre,2150,"75ø20'8,2""W","6ø4'25,6""N","2,591.12",204.02,05148,-75.34,6.07
8,23080300,PM,Carmen El,2180,"75ø20'0""W","6ø5'0""N","2,779.30",204.38,05148,-75.33,6.08
9,23080790,PM,Linda La,2620,"75ø17'0""W","5ø57'0""N","4,686.50",255.38,05148,-75.28,5.95
10,23080350,PM,Santuario,2150,"75ø16'0""W","6ø8'0""N","3,021.40",242.21,05697,-75.27,6.13
11,27010750,PM,Entrerrios,2285,"75ø29'0""W","6ø34'0""N","1,783.01",193.00,05264,-75.48,6.57
12,27010830,PM,San Isidro,2300,"75ø30'56,7""W","6ø33'47,6""N","2,155.12",175.24,05264,-75.52,6.56
13,27010930,PG,Ayura,1770,"75ø38'0""W","6ø10'0""N","1,777.17",215.32,05266,-75.63,6.17
14,26200150,PM,Fredonia,1685,"75ø41'6,4""W","5ø56'12,3""N","2,754.10",165.19,05282,-75.69,5.94
15,26175040,CO,Tunez Hda,655,"75ø39'3,5""W","5ø48'0,7""N","1,768.43",177.09,05282,-75.65,5.80
16,11110030,PM,Fuemia,905,"76ø15'8""W","6ø51'29""N","1,758.02",123.32,05284,-76.25,6.86
17,11115040,CO,Musinga,1330,"76ø11'27""W","6ø47'13""N","2,274.29",240.51,05284,-76.19,6.79
18,11110010,PM,Normal Sta Teresa,1370,"76ø8'1""W","6ø45'48""N","2,650.97",198.75,05284,-76.13,6.76
19,11110110,PG,Boqueron de Toyo,2000,"75ø58'39""W","6ø41'58""N","1,987.79",NaN,05306,-75.98,6.70

In [14]:
conest = pd.DataFrame(Estaciones["Depmun"].unique(),columns=["Depmun"])
conest.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 806 entries, 0 to 805
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Depmun  806 non-null    object
dtypes: object(1)
memory usage: 6.4+ KB

<h1 style="color:red;"> Ejemplo 19 </h1>

Conjunto de datos con todos los municipios del país, que incluye una variable que informa el número de estaciones de monitoreo climático con que cuenta cada municipio.

In [138]:
Emon = (Estaciones
        .groupby(["Depmun"])
        .agg(nem=("CODIGO","count")).reset_index()
       )

# Nota
# Al momernto de hacer una union tiene que ser del mismo tipo la varible por la que este uniendo

e19 = (Municipios
      .merge(Emon,left_on=["Depmun"],right_on=["Depmun"],how="left")
      .eval('''nest = nem.fillna(0).values''')
      .drop(columns=["nem"])
      .sort_values(by=["Dep","Poblacion"],ascending=[True,False]).reset_index(drop=True)
      )

e19.info()
e19.head(20)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1118 entries, 0 to 1117
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Departamento  1118 non-null   object
 1   Dep           1118 non-null   object
 2   Municipio     1118 non-null   object
 3   Depmun        1118 non-null   object
 4   Superficie    1117 non-null   float64
 5   Poblacion     1118 non-null   float64
 6   Irural        1118 non-null   float64
 7   Region        1118 non-null   object
 8   Tipo          1118 non-null   object
 9   denspobl      1117 non-null   float64
 10  Zona          1118 non-null   object
 11  Municipio2    1118 non-null   object
 12  Iguales       1118 non-null   bool
 13  denspoblC     1117 non-null   object
 14  nest          1118 non-null   float64
dtypes: bool(1), float64(5), object(9)
memory usage: 123.5+ KB

,Departamento,Dep,Municipio,Depmun,Superficie,Poblacion,Irural,Region,Tipo,denspobl,Zona,Municipio2,Iguales,denspoblC,nest
0,Antioquia,05,Medellín,05001,374.83,"2,483,545.00",5.00,Eje Cafetero,Capital,"6,625.78",Urbano,medellin,False,Alta,10.00
1,Antioquia,05,Bello,05088,147.76,"538,527.00",12.00,Eje Cafetero,Otros,"3,644.65",Urbano,bello,False,Alta,3.00
2,Antioquia,05,Itagui,05360,19.65,"283,794.00",0.00,Eje Cafetero,Otros,"14,442.77",Urbano,itagui,True,Alta,0.00
3,Antioquia,05,Envigado,05266,78.00,"236,114.00",8.00,Eje Cafetero,Otros,"3,027.23",Urbano,envigado,False,Alta,1.00
4,Antioquia,05,Rionegro,05615,195.94,"139,553.00",24.00,Eje Cafetero,Otros,712.22,Urbano,rionegro,False,Alta,4.00
5,Antioquia,05,Turbo,05837,"2,919.54","127,565.00",48.00,Eje Cafetero,Otros,43.69,Rural,turbo,False,Media,6.00
6,Antioquia,05,Apartadó,05045,535.17,"124,647.00",34.00,Eje Cafetero,Otros,232.91,Urbano,apartado,False,Alta,3.00
7,Antioquia,05,Caucasia,05154,"1,429.12","93,044.00",45.00,Eje Cafetero,Otros,65.11,Rural,caucasia,False,Media,6.00
8,Antioquia,05,Sabaneta,05631,15.84,"85,484.00",10.00,Eje Cafetero,Otros,"5,398.31",Urbano,sabaneta,False,Alta,0.00
9,Antioquia,05,Caldas,05129,132.76,"81,658.00",24.00,Eje Cafetero,Otros,615.10,Urbano,caldas,False,Alta,2.00
10,Antioquia,05,Copacabana,05212,67.76,"80,000.00",20.00,Eje Cafetero,Otros,"1,180.63",Urbano,copacabana,False,Alta,0.00
11,Antioquia,05,La Estrella,05380,36.63,"73,696.00",16.00,Eje Cafetero,Otros,"2,011.80",Urbano,la estrella,False,Alta,0.00
12,Antioquia,05,La Ceja,05376,132.71,"66,746.00",28.00,Eje Cafetero,Otros,502.93,Urbano,la ceja,False,Alta,0.00
13,Antioquia,05,Marinilla,05440,114.87,"66,399.00",27.00,Eje Cafetero,Otros,578.03,Urbano,marinilla,False,Alta,1.00
14,Antioquia,05,El Carmen De Viboral,05148,423.65,"61,122.00",38.00,Eje Cafetero,Otros,144.28,Urbano,el carmen de viboral,False,Alta,3.00
15,Antioquia,05,Chigorodó,05172,721.68,"58,684.00",43.00,Eje Cafetero,Otros,81.32,Rural,chigorodo,False,Media,2.00
16,Antioquia,05,Guarne,05318,151.81,"56,774.00",30.00,Eje Cafetero,Otros,373.98,Urbano,guarne,False,Alta,2.00
17,Antioquia,05,Barbosa,05079,205.67,"53,242.00",32.00,Eje Cafetero,Otros,258.88,Urbano,barbosa,False,Alta,2.00
18,Antioquia,05,Girardota,05308,82.86,"53,162.00",25.00,Eje Cafetero,Otros,641.62,Urbano,girardota,False,Alta,3.00
19,Antioquia,05,El Bagre,05250,"1,560.25","52,925.00",51.00,Eje Cafetero,Otros,33.92,Rural,el bagre,True,Media,2.00

<h1 style="color:red;"> Ejemplo 20 </h1>

Existen municipios que no tienen ninguna estación de monitoreo climático? Cuantos? Cuales?

In [139]:
e20 = (Municipios
       .merge(Emon,left_on=["Depmun"],right_on=["Depmun"],how="left")
       .query("nem.isnull().values") # Filtro los NA
       .sort_values(by=["Depmun"],ascending=[True]).reset_index(drop=True)
       .drop(columns="nem")
      )

emons = Emon["Depmun"]
e20a = (Municipios
        .query("Depmun not in @emons")
        .sort_values(by=["Depmun"],ascending=[True]).reset_index(drop=True)
       ) 

e20b = (e19
        .query("nest==0")
        .drop(columns=["nest"])
        .sort_values(by=["Depmun"],ascending=[True]).reset_index(drop=True)
       ) 
comparacion(e20,e20a)

True

<h1 style="color:red;"> Ejemplo 21 </h1>

Copia de Estaciones que solo considera estaciones de monitoreo localizadas como máximo a 2000 metros de altura sobre el nivel del mar, y que incluye los nombres del municipio y del departamento donde están ubicadas las estaciones.

In [140]:
e21=(Estaciones
     .merge(Municipios[["Municipio","Departamento","Dep","Depmun"]],left_on=["Depmun"],right_on=["Depmun"],how="left")
     .query("ELEV <= 2000")
     .sort_values(by=["Depmun","CODIGO"],ascending=[True,True]).reset_index(drop=True)
    )

e21.info()
e21.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1537 entries, 0 to 1536
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CODIGO        1537 non-null   object
 1   CAT           1537 non-null   object
 2   NOMBRE        1537 non-null   object
 3   ELEV          1537 non-null   int64
 4   longitud2     1537 non-null   object
 5   latitud2      1537 non-null   object
 6   PRECIP        1537 non-null   float64
 7   NDLL          1436 non-null   float64
 8   Depmun        1537 non-null   object
 9   longitud      1537 non-null   float64
 10  latitud       1525 non-null   float64
 11  Municipio     184 non-null    object
 12  Departamento  184 non-null    object
 13  Dep           184 non-null    object
dtypes: float64(4), int64(1), object(9)
memory usage: 168.2+ KB

,CODIGO,CAT,NOMBRE,ELEV,longitud2,latitud2,PRECIP,NDLL,Depmun,longitud,latitud,Municipio,Departamento,Dep
0,27010380,PG,San Antonio de Pra,2000,"75ø40'0""W","6ø11'0""N","2,116.05",198.54,05001,-75.67,6.18,Medellín,Antioquia,05
1,27010450,PG,Villahermosa Plant,1690,"75ø33'0""W","6ø16'0""N","1,608.92",178.40,05001,-75.55,6.27,Medellín,Antioquia,05
2,27010460,PG,San Cristobal,1890,"75ø38'0""W","6ø17'0""N","1,768.06",213.07,05001,-75.63,6.28,Medellín,Antioquia,05
3,27010470,PG,Medellin Miguel Ag,1549,"75ø34'0""W","6ø15'0""N","1,470.31",201.56,05001,-75.57,6.25,Medellín,Antioquia,05
4,27015070,SP,Apto Olaya Herrera,1490,"75ø35'20,3""W","6ø13'14,2""N","1,685.33",224.60,05001,-75.59,6.22,Medellín,Antioquia,05
5,11110020,PG,Abriaqui,1920,"76ø4'30""W","6ø38'33""N","2,140.75",203.74,05004,-76.08,6.64,Abriaquí,Antioquia,05
6,27010850,PM,Amalfi,1530,"75ø4'38""W","6ø54'20""N","3,173.60",196.45,05031,-75.08,6.91,Amalfi,Antioquia,05
7,27010890,PM,Cueva Santa,1550,"75ø2'18,1""W","6ø57'32,4""N","3,052.63",160.70,05031,-75.04,6.96,Amalfi,Antioquia,05
8,27010960,PM,Monos Hda,1100,"74ø54'7,7""W","6ø53'55""N","3,065.79",171.85,05031,-74.90,6.90,Amalfi,Antioquia,05
9,26190100,PM,Sta Barbara,1600,"75ø54'0,3""W","5ø33'50,3""N","2,409.90",219.88,05034,-75.90,5.56,Andes,Antioquia,05

<h2 style="color:black;"> Unión horizontal de conjuntos de datos </h2>

In [141]:
df1 = pd.DataFrame({
  "age": [32, 35, 59, 79],
  "name": ["Messi", "Cr7", "Maradona", "Pele"]
})
df1.info()
df1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     4 non-null      int64
 1   name    4 non-null      object
dtypes: int64(1), object(1)
memory usage: 192.0+ bytes

   age      name
0   32     Messi
1   35       Cr7
2   59  Maradona
3   79      Pele

In [142]:
df2 = pd.DataFrame({
  "year": [1947, 1976, 1972],
  "name": ["Cruyf", "Ronaldo", "Zidane"]
})
df2.info()
df2

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   year    3 non-null      int64
 1   name    3 non-null      object
dtypes: int64(1), object(1)
memory usage: 176.0+ bytes

   year     name
0  1947    Cruyf
1  1976  Ronaldo
2  1972   Zidane

In [145]:
uh1 = pd.concat([df1,df2],axis=1).reset_index(drop=True)
uh1.info()
uh1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     4 non-null      int64
 1   name    4 non-null      object
 2   year    3 non-null      float64
 3   name    3 non-null      object
dtypes: float64(1), int64(1), object(2)
memory usage: 256.0+ bytes

   age      name     year     name
0   32     Messi 1,947.00    Cruyf
1   35       Cr7 1,976.00  Ronaldo
2   59  Maradona 1,972.00   Zidane
3   79      Pele      NaN      NaN

In [147]:
uh2 = pd.concat([df2,df1],axis=1).reset_index(drop=True)
uh2.info()
uh2

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   year    3 non-null      float64
 1   name    3 non-null      object
 2   age     4 non-null      int64
 3   name    4 non-null      object
dtypes: float64(1), int64(1), object(2)
memory usage: 256.0+ bytes

      year     name  age      name
0 1,947.00    Cruyf   32     Messi
1 1,976.00  Ronaldo   35       Cr7
2 1,972.00   Zidane   59  Maradona
3      NaN      NaN   79      Pele

<h2 style="color:black;"> Unión vertical de conjuntos de datos </h2>

In [149]:
uv1 = pd.concat([df1,df2],axis=0).reset_index(drop=True)
uv1.info()
uv1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     4 non-null      float64
 1   name    7 non-null      object
 2   year    3 non-null      float64
dtypes: float64(2), object(1)
memory usage: 296.0+ bytes

    age      name     year
0 32.00     Messi      NaN
1 35.00       Cr7      NaN
2 59.00  Maradona      NaN
3 79.00      Pele      NaN
4   NaN     Cruyf 1,947.00
5   NaN   Ronaldo 1,976.00
6   NaN    Zidane 1,972.00

In [152]:
uv2 = pd.concat([df2,df1],axis=0).reset_index(drop=True)
uv2.info()
uv2

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   year    3 non-null      float64
 1   name    7 non-null      object
 2   age     4 non-null      float64
dtypes: float64(2), object(1)
memory usage: 296.0+ bytes

      year      name   age
0 1,947.00     Cruyf   NaN
1 1,976.00   Ronaldo   NaN
2 1,972.00    Zidane   NaN
3      NaN     Messi 32.00
4      NaN       Cr7 35.00
5      NaN  Maradona 59.00
6      NaN      Pele 79.00

 <center><h1 style="color:red;"> Ejercicio datos Brasil </h1></center>

<h3 style="color:blue;"> Importa los DataFrames </h3>

In [15]:
MuniBR = pd.read_excel("Brasil.xlsx",sheet_name=0,header=0)
MuniBR.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5570 entries, 0 to 5569
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   CODESTAD  5570 non-null   int64
 1   CODMUNIC  5570 non-null   int64
 2   POB       5570 non-null   int64
 3   SUP       5570 non-null   float64
 4   NOMMUNIC  5570 non-null   object
dtypes: float64(1), int64(3), object(1)
memory usage: 217.7+ KB

In [16]:
MuniBR.head(10)

   CODESTAD  CODMUNIC     POB       SUP                  NOMMUNIC
0        11   1100015   22516  7,067.13  A/+lta Flor?esta D'Oeste
1        11   1100023  111148  4,426.57              Ar¡*i/quemes
2        11   1100031    5067  1,314.35                 Cab¡i^xi¡
3        11   1100049   86416  3,793.00                 Cac$oa{|l
4        11   1100056   16088  2,783.30             Ce~:rej=eiras
5        11   1100064   15213  1,451.06      Co;lo$rado do Oes|te
6        11   1100072    7052  3,060.32             Cor!u]mbiar*a
7        11   1100080   19255  4,987.18          Co{sta Marqu&?es
8        11   1100098   33009  4,518.04        E+^¿spigão D'Oeste
9        11   1100106   46930 24,856.88          G!u/ajará-Mi)rim

In [17]:
Estados = pd.read_excel("Brasil.xlsx",sheet_name=1,header=0)
Estados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   REGIAO    27 non-null     object
 1   CODESTAD  27 non-null     int64
 2   NOMESTAD  27 non-null     object
dtypes: int64(1), object(2)
memory usage: 776.0+ bytes

In [ ]:
Estados.head(10)

            REGIAO  CODESTAD      NOMESTAD
0     Região Norte        11   Ro|n¿dônia*
1     Região Norte        12       Ac(=re)
2     Região Norte        13   Am]^azonas¡
3     Região Norte        14    R_(orai=ma
4     Região Norte        15       Par_?~á
5     Região Norte        16      Ama):~pá
6     Região Norte        17  Tocanti}/(ns
7  Região Nordeste        21   M|aranhão$/
8  Região Nordeste        22      Pi!auí_?
9  Região Nordeste        23      Cear!á;~

In [18]:
Costeros = pd.read_excel("Brasil.xlsx",sheet_name=2,header=0)
Costeros.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 443 entries, 0 to 442
Data columns (total 1 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   CODMUNIC  443 non-null    int64
dtypes: int64(1)
memory usage: 3.6 KB

In [ ]:
Costeros.head(10)

   CODMUNIC
0   4323804
1   4323002
2   4322327
3   4321832
4   4321667
5   4321600
6   4321501
7   4321436
8   4321352
9   4321105

<h4 style="color:blue;">1. ¿Cuál es la región (REGIAO) que se compone del menor número de municipios?</h4>

In [20]:
MuniBR2 = (MuniBR
           .merge(Estados,left_on="CODESTAD",right_on="CODESTAD",how="left")
          )

MuniBR2.head(10)

,CODESTAD,CODMUNIC,POB,SUP,NOMMUNIC,REGIAO,NOMESTAD
0,11,1100015,22516,"7,067.13",A/+lta Flor?esta D'Oeste,Região Norte,Ro|n¿dônia*
1,11,1100023,111148,"4,426.57",Ar¡*i/quemes,Região Norte,Ro|n¿dônia*
2,11,1100031,5067,"1,314.35",Cab¡i^xi¡,Região Norte,Ro|n¿dônia*
3,11,1100049,86416,"3,793.00",Cac$oa{|l,Região Norte,Ro|n¿dônia*
4,11,1100056,16088,"2,783.30",Ce~:rej=eiras,Região Norte,Ro|n¿dônia*
5,11,1100064,15213,"1,451.06",Co;lo$rado do Oes|te,Região Norte,Ro|n¿dônia*
6,11,1100072,7052,"3,060.32",Cor!u]mbiar*a,Região Norte,Ro|n¿dônia*
7,11,1100080,19255,"4,987.18",Co{sta Marqu&?es,Região Norte,Ro|n¿dônia*
8,11,1100098,33009,"4,518.04",E+^¿spigão D'Oeste,Região Norte,Ro|n¿dônia*
9,11,1100106,46930,"24,856.88",G!u/ajará-Mi)rim,Região Norte,Ro|n¿dônia*

In [21]:
(MuniBR2
 .groupby(["REGIAO"])
 .agg(Muni=("CODMUNIC","count")).reset_index()
 .sort_values(by=["Muni"],ascending=True).reset_index(drop= True)
 .head(n=2)
)

                REGIAO  Muni
0         Região Norte   450
1  Região Centro-Oeste   467

<h4 style="color:blue;">2. ¿Cuál es la región (REGIAO) que se compone del mayor número de habitantes? </h4>

In [ ]:
(MuniBR2
 .groupby(["REGIAO"])
 .agg(POB=("POB","sum")).reset_index()
 .sort_values(by=["POB"],ascending=False).reset_index(drop= True)
 .head(n=2)
)

            REGIAO       POB
0   Região Sudeste  89632912
1  Região Nordeste  57667842

<h4 style="color:blue;" >3. ¿Cuál es la región (REGIAO) con la menor superficie? </h4>

In [ ]:
(MuniBR2
 .groupby(["REGIAO"])
 .agg(SUP=("SUP","sum")).reset_index()
 .sort_values(by=["SUP"],ascending=True).reset_index(drop= True)
 .head(n=2)
)

           REGIAO        SUP
0      Região Sul 563,650.94
1  Região Sudeste 924,558.34

<h4 style="color:blue;"> 4. ¿Cuál es la región (REGIAO) más homogénea con respecto al tamaño, en número de habitantes, de los municipios que la componen? Use el coeficiente de variación como medida de heterogeneidad.</h4>

In [22]:
def cv(x): 
    return(x.std()/x.mean())

(MuniBR2
 .groupby(["REGIAO"])
 .agg(CV=("POB",cv)).reset_index()
 .sort_values(by=["CV"],ascending=True).reset_index(drop= True)
 .head(n=2)
)

         REGIAO   CV
0  Região Norte 3.34
1    Região Sul 3.47

<h4 style="color:blue;"> 5. ¿Cuál es la región (REGIAO) más heterogénea con respecto al tamaño, en superficie, de los municipios que la componen? Use el coeficiente de variación como medida de heterogeneidad. </h4>

In [23]:
def cv(x): 
    return(x.std()/x.mean())

(MuniBR2
 .groupby(["REGIAO"])
 .agg(CV=("SUP",cv)).reset_index()
 .sort_values(by=["CV"],ascending=False).reset_index(drop= True)
 .head(n=2)
)

            REGIAO   CV
0     Região Norte 1.99
1  Região Nordeste 1.57

<h4 style="color:blue;" > 6. ¿Cuál es el estado (CODESTAD y NOMESTAD) que se componen del mayor número de municipios costeros? </h4>

In [43]:
# Crea una varivle nueva llamada costeros en el DataFrame Costeros
Costeros =(Costeros
          .eval(""" costero =1 """)
          )

MuniBR3 = (MuniBR2
           .merge(Costeros,left_on="CODMUNIC",right_on="CODMUNIC",how="left")
           .eval('''costero = costero.fillna(0).values''')
          )


MuniBR3.head(10)

,CODESTAD,CODMUNIC,POB,SUP,NOMMUNIC,REGIAO,NOMESTAD,costero
0,11,1100015,22516,"7,067.13",A/+lta Flor?esta D'Oeste,Região Norte,Ro|n¿dônia*,0.00
1,11,1100023,111148,"4,426.57",Ar¡*i/quemes,Região Norte,Ro|n¿dônia*,0.00
2,11,1100031,5067,"1,314.35",Cab¡i^xi¡,Região Norte,Ro|n¿dônia*,0.00
3,11,1100049,86416,"3,793.00",Cac$oa{|l,Região Norte,Ro|n¿dônia*,0.00
4,11,1100056,16088,"2,783.30",Ce~:rej=eiras,Região Norte,Ro|n¿dônia*,0.00
5,11,1100064,15213,"1,451.06",Co;lo$rado do Oes|te,Região Norte,Ro|n¿dônia*,0.00
6,11,1100072,7052,"3,060.32",Cor!u]mbiar*a,Região Norte,Ro|n¿dônia*,0.00
7,11,1100080,19255,"4,987.18",Co{sta Marqu&?es,Região Norte,Ro|n¿dônia*,0.00
8,11,1100098,33009,"4,518.04",E+^¿spigão D'Oeste,Região Norte,Ro|n¿dônia*,0.00
9,11,1100106,46930,"24,856.88",G!u/ajará-Mi)rim,Região Norte,Ro|n¿dônia*,0.00

In [44]:
(MuniBR3
 .query("costero == 1")
 .groupby(["CODESTAD","NOMESTAD"])
 .agg(NMC=("CODMUNIC","count")).reset_index()
 .sort_values(by=["NMC"],ascending=False).reset_index(drop=True)
)

    CODESTAD                NOMESTAD  NMC
0         29                Bahia]][   53
1         15                 Par_?~á   47
2         42       Santa C&atar?i)na   41
3         21             M|aranhão$/   40
4         43    Rio G{=rande )do Sul   39
5         33       R_io de¡ Jane{iro   33
6         24  Rio| Gran^de+ do Norte   29
7         27              Al/a}goa%s   27
8         28              Se:r?gipe_   24
9         23                Cear!á;~   23
10        32       E?%spírito San~to   18
11        26           Per}n(amb¿uco   17
12        35            São ¡P{aulo$   16
13        25              Paraíb}¿a|   13
14        16                Ama):~pá   11
15        41               P=ara¿n)á    7
16        22                Pi!auí_?    5

<h4 style="color:blue;"> 7. ¿Cuál es el estado (CODESTAD y NOMESTAD) con la mayor superficie en municipios costeros? es decir, ¿cual es el estado para el que la suma de la superficie de sus municipios costeros es la mayor del país? </h4>

In [45]:
(MuniBR3
 .query("costero == 1")
 .groupby(["CODESTAD","NOMESTAD"])
 .agg(SUPT=("SUP","sum")).reset_index()
 .sort_values(by=["SUPT"],ascending=False).reset_index(drop=True)
)

    CODESTAD                NOMESTAD       SUPT
0         15                 Par_?~á 129,795.03
1         16                Ama):~pá  84,950.56
2         29                Bahia]][  39,165.07
3         21             M|aranhão$/  37,488.25
4         43    Rio G{=rande )do Sul  32,905.04
5         33       R_io de¡ Jane{iro  17,484.58
6         23                Cear!á;~  15,523.48
7         32       E?%spírito San~to  13,775.24
8         24  Rio| Gran^de+ do Norte  10,104.24
9         42       Santa C&atar?i)na   9,874.48
10        35            São ¡P{aulo$   7,783.29
11        27              Al/a}goa%s   7,422.17
12        41               P=ara¿n)á   6,055.34
13        28              Se:r?gipe_   5,720.55
14        26           Per}n(amb¿uco   3,738.52
15        25              Paraíb}¿a|   2,595.16
16        22                Pi!auí_?   2,435.04

<h4 style="color:blue;">8. ¿Cuál es el estado (CODESTAD y NOMESTAD) con la mayor población en municipios costeros? es decir, ¿cual es el estado para el que la suma de la población en sus municipios costeros es la mayor del país?</h4>

In [ ]:
(MuniBR3
 .query("costero == 1")
 .groupby(["CODESTAD","NOMESTAD"])
 .agg(POB=("POB","sum")).reset_index()
 .sort_values(by=["POB"],ascending=False).reset_index(drop=True)
)

    CODESTAD                NOMESTAD       POB
0         33       R_io de¡ Jane{iro  14489416
1         29                Bahia]][   5519298
2         15                 Par_?~á   4140577
3         23                Cear!á;~   4063811
4         26           Per}n(amb¿uco   3930140
5         42       Santa C&atar?i)na   3103132
6         32       E?%spírito San~to   2685369
7         35            São ¡P{aulo$   2298606
8         21             M|aranhão$/   2295016
9         24  Rio| Gran^de+ do Norte   2070268
10        27              Al/a}goa%s   1677007
11        43    Rio G{=rande )do Sul   1505342
12        28              Se:r?gipe_   1329928
13        25              Paraíb}¿a|   1282131
14        16                Ama):~pá    771031
15        41               P=ara¿n)á    302544
16        22                Pi!auí_?    207282

<h4 style="color:blue;">9. ¿Cuál es el estado (CODESTAD y NOMESTAD) con la mayor densidad poblacional en municipios costeros?, es decir, ¿cual es el estado para el que la densidad poblacional en sus municipios costeros es la mayor del país?</h4>

In [ ]:
(MuniBR3
 .query("costero == 1")
 .groupby(["CODESTAD","NOMESTAD"])
 .agg(POB=("POB","sum"),
     SUP=("SUP","sum")).reset_index()
 .eval(""" DP = POB/SUP """)
 .sort_values(by=["DP"],ascending=False).reset_index(drop=True)
)

    CODESTAD                NOMESTAD       POB        SUP       DP
0         26           Per}n(amb¿uco   3930140   3,738.52 1,051.25
1         33       R_io de¡ Jane{iro  14489416  17,484.58   828.70
2         25              Paraíb}¿a|   1282131   2,595.16   494.05
3         42       Santa C&atar?i)na   3103132   9,874.48   314.26
4         35            São ¡P{aulo$   2298606   7,783.29   295.33
5         23                Cear!á;~   4063811  15,523.48   261.78
6         28              Se:r?gipe_   1329928   5,720.55   232.48
7         27              Al/a}goa%s   1677007   7,422.17   225.95
8         24  Rio| Gran^de+ do Norte   2070268  10,104.24   204.89
9         32       E?%spírito San~to   2685369  13,775.24   194.94
10        29                Bahia]][   5519298  39,165.07   140.92
11        22                Pi!auí_?    207282   2,435.04    85.12
12        21             M|aranhão$/   2295016  37,488.25    61.22
13        41               P=ara¿n)á    302544   6,055.34    49.96
14        43    Rio G{=rande )do Sul   1505342  32,905.04    45.75
15        15                 Par_?~á   4140577 129,795.03    31.90
16        16                Ama):~pá    771031  84,950.56     9.08

<h4 style="color:blue;">10 ¿Cuál es el estado (CODESTAD y NOMESTAD) con la mayor proporción de superficie en municipios costeros?, es decir, ¿cual es el estado para el que la proporción de su superficie que corresponde a municipios costeros es la mayor del país?</h4>

In [74]:
SUPT = (MuniBR3
        .groupby(["CODESTAD","NOMESTAD"])
        .agg(SUPT=("SUP","sum")).reset_index()
        .sort_values(by=["SUPT"],ascending=False).reset_index(drop=True)
       )

SUPC = (MuniBR3
        .query("costero == 1")
        .groupby(["CODESTAD"])
        .agg(SUPC=("SUP","sum")).reset_index()
        .sort_values(by=["SUPC"],ascending=False).reset_index(drop=True)
       )

PRC  = (SUPT
        .merge(SUPC,left_on="CODESTAD",right_on="CODESTAD",how="left")
        .eval('''SUPC = SUPC.fillna(0).values''')
        .eval('''PRC = 100*(SUPC/SUPT)''')
        .drop(columns=["SUPC","SUPT"])
        .sort_values(by=["PRC"],ascending=False).reset_index(drop=True)
       )

PRC.head(10)

   CODESTAD                NOMESTAD   PRC
0        16                Ama):~pá 59.63
1        33       R_io de¡ Jane{iro 39.96
2        32       E?%spírito San~to 29.90
3        27              Al/a}goa%s 26.67
4        28              Se:r?gipe_ 26.08
5        24  Rio| Gran^de+ do Norte 19.13
6        43    Rio G{=rande )do Sul 12.25
7        21             M|aranhão$/ 11.37
8        23                Cear!á;~ 10.43
9        15                 Par_?~á 10.42

In [80]:
# Otra forma de hacerlo
(MuniBR3
.eval("SUP2=SUP*costero")
.groupby(["CODESTAD","NOMESTAD"])
.agg(superficie=("SUP","sum"),
     superficie2=("SUP2","sum")).reset_index()
.eval('''porcen=100*superficie2/superficie''') 
.sort_values(by=["porcen"],ascending=[False]).reset_index(drop=True)
.head(2)
)

   CODESTAD           NOMESTAD  superficie  superficie2  porcen
0        16           Ama):~pá  142,470.76    84,950.56   59.63
1        33  R_io de¡ Jane{iro   43,750.43    17,484.58   39.96

<h4 style="color:blue;">11. ¿Cuál es el estado (CODESTAD y NOMESTAD) con la mayor proporción de población en municipios costeros?, es decir, ¿cual es el estado para el que la proporción de su población que habita en municipios costeros es la mayor del país?</h4>

In [83]:
(MuniBR3
.eval("POB2=POB*costero")
.groupby(["CODESTAD","NOMESTAD"])
.agg(poblacion=("POB","sum"),
     poblacion2=("POB2","sum")).reset_index()
.eval('''porcen=100*poblacion2/poblacion''') 
.sort_values(by=["porcen"],ascending=[False]).reset_index(drop=True)
.head(2)
)

   CODESTAD           NOMESTAD  poblacion    poblacion2  porcen
0        16           Ama):~pá     877613    771,031.00   87.86
1        33  R_io de¡ Jane{iro   17463349 14,489,416.00   82.97

<h4 style="color:blue;">12. De los estados que no tienen ningún municipio costero, ¿cuál (CODESTAD y NOMESTAD) es el más homogéneo con respecto al tamaño, en número de habitantes, de los municipios que lo componen? Use el coeficiente de variación como medida de heterogeneidad.</h4>

In [84]:
(MuniBR3
.groupby(["CODESTAD","NOMESTAD"])
.agg(mean=("POB","mean"),
     std=("POB","std"),
     costeros=("costero","sum")).reset_index()
.eval('''cv=std/mean''')     
.query("costeros==0") 
.sort_values(by=["cv"],ascending=[True]).reset_index(drop=True)
.head(2)
)

   CODESTAD     NOMESTAD      mean       std  costeros   cv
0        12      Ac(=re) 41,221.64 86,435.72      0.00 2.10
1        11  Ro|n¿dônia* 34,909.19 77,891.69      0.00 2.23

<h4 style="color:blue;">13. De los estados que no tienen ningún municipio costero, ¿cuál (CODESTAD y NOMESTAD) es el más heterogéneo con respecto al tamaño, en superficie, de los municipios que lo componen? Use el coeficiente de variación como medida de heterogeneidad.</h4>

In [85]:
(MuniBR3
.groupby(["CODESTAD","NOMESTAD"])
.agg(mean=("SUP","mean"),
     std=("SUP","std"),
     costeros=("costero","sum")).reset_index()
.eval('''cv=std/mean''')     
.query("costeros==0") 
.sort_values(by=["cv"],ascending=[False]).reset_index(drop=True)
.head(2)
)

   CODESTAD               NOMESTAD     mean      std  costeros   cv
0        50  Ma;to Gro/sso; do Sul 4,520.79 7,635.62      0.00 1.69
1        31        M&in~as Gera{is   687.59   965.85      0.00 1.40

<h4 style="color:blue;"> 14. De los estados que no tienen ningún municipio costero, ¿cuál (CODESTAD y NOMESTAD) tiene la menor densidad poblacional? </h4>

In [86]:
(MuniBR3
.groupby(["CODESTAD","NOMESTAD"])
.agg(SUPT=("SUP","sum"),
     POBT=("POB","sum"),
     costeros=("costero","sum")).reset_index()
.eval('''DP=POBT/SUPT''')     
.query("costeros==0") 
.sort_values(by=["DP"],ascending=[True]).reset_index(drop=True)
.head(2)
)

   CODESTAD     NOMESTAD         SUPT     POBT  costeros   DP
0        13  Am]^azonas¡ 1,559,255.88  4269995      0.00 2.74
1        14   R_(orai=ma   223,644.53   652713      0.00 2.92